<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Basic Statistics | Data Analysis and Visualization in R Using smplot</title>
  <meta name="description" content="Chapter 7 Basic Statistics | Data Analysis and Visualization in R Using smplot" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Basic Statistics | Data Analysis and Visualization in R Using smplot" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Basic Statistics | Data Analysis and Visualization in R Using smplot" />
  
  
  

<meta name="author" content="Seung Hyun Min" />


<meta name="date" content="2022-03-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-analysis---area-under-a-curve.html"/>
<link rel="next" href="recreating-figures-from-front.-genetics-2021.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Dataviz with smplot</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#major-updates-on-smplot"><i class="fa fa-check"></i>Major updates on smplot</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#please-cite-this-paper-when-smplot-is-used"><i class="fa fa-check"></i>Please cite this paper when smplot is used</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-r-and-ggplot2-experts"><i class="fa fa-check"></i>For R and ggplot2 experts</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#issues-and-contact"><i class="fa fa-check"></i>Issues and contact</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html"><i class="fa fa-check"></i><b>1</b> Download RStudio &amp; Basics of R</a>
<ul>
<li class="chapter" data-level="1.1" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#setting-up-rstudio"><i class="fa fa-check"></i><b>1.1</b> Setting up RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#why-use-r-for-data-visualization"><i class="fa fa-check"></i>Why use R for data visualization?</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#other-available-resources-for-r"><i class="fa fa-check"></i>Other available resources for R</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#download-requirements-for-rstudio"><i class="fa fa-check"></i>Download requirements for RStudio</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#open-rstudio"><i class="fa fa-check"></i>Open RStudio</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#lets-make-a-folder-and-set-it-as-working-directory"><i class="fa fa-check"></i>Let’s make a folder and set it as working directory</a></li>
<li class="chapter" data-level="1.1.1" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#how-to-run-your-code"><i class="fa fa-check"></i><b>1.1.1</b> How to run your code</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#basics-of-r"><i class="fa fa-check"></i><b>1.2</b> Basics of R</a>
<ul>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#lets-type-some-codes"><i class="fa fa-check"></i>Let’s type some codes</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#how-can-i-learn-most-effectively-with-the-notes"><i class="fa fa-check"></i>How can I learn most effectively with the notes?</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#more-installation"><i class="fa fa-check"></i>More installation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html"><i class="fa fa-check"></i><b>2</b> Basics of ggplot2 and Correlation Plot</a>
<ul>
<li class="chapter" data-level="2.1" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#uploading-data"><i class="fa fa-check"></i><b>2.1</b> Uploading data</a>
<ul>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#sample-data-mpg"><i class="fa fa-check"></i>Sample data: mpg</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#basics-of-ggplot2"><i class="fa fa-check"></i><b>2.2</b> Basics of ggplot2</a>
<ul>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#lets-make-some-graphs"><i class="fa fa-check"></i>Let’s make some graphs</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#how-ggplot-works"><i class="fa fa-check"></i>How ggplot works</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#different-color-of-points-for-each-unique-group"><i class="fa fa-check"></i>Different color of points for each unique group</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#different-color-shape-for-each-group"><i class="fa fa-check"></i>Different color &amp; shape for each group</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#same-shape-across-all-groups"><i class="fa fa-check"></i>Same shape across all groups</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#exercise-try-changing-the-shape-of-the-points-to-the-circle-with-the-border."><i class="fa fa-check"></i>Exercise: try changing the shape of the points to the circle with the border.</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#how-do-we-draw-the-best-fit-line-of-the-graph"><i class="fa fa-check"></i>How do we draw the best-fit line of the graph?</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#geom_point-geom_smooth"><i class="fa fa-check"></i>geom_point() + geom_smooth()</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#writing-shorter-codes"><i class="fa fa-check"></i>Writing shorter codes</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#improve-data-visualization-using-smplot"><i class="fa fa-check"></i><b>2.3</b> Improve Data Visualization using smplot</a>
<ul>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#positive-relationship-between-x--and-y-axes"><i class="fa fa-check"></i>Positive relationship between x- and y-axes</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#reporting-statistics-from-a-paired-correlation"><i class="fa fa-check"></i>Reporting statistics from a paired correlation</a></li>
<li><a href="basics-of-ggplot2-and-correlation-plot.html#fill-0f993d-vs-fill-green"><code>fill = '#0f993d'</code> vs <code>fill = 'green'</code></a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#different-color-for-each-group-but-with-other-colors"><i class="fa fa-check"></i>Different color for each group but with other colors</a></li>
<li><a href="basics-of-ggplot2-and-correlation-plot.html#lets-save-the-plot-as-an-image-in-your-folder-learnr-by-using-the-variable-figure1.">Let’s save the plot as an image in your folder <strong>LearnR</strong> by using the variable <strong>figure1</strong>.</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#summary"><i class="fa fa-check"></i><b>2.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html"><i class="fa fa-check"></i><b>3</b> Boxplot and Violin Plot</a>
<ul>
<li class="chapter" data-level="3.1" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#upload-sample-data-csv-file-in-rstudio"><i class="fa fa-check"></i><b>3.1</b> Upload Sample Data (csv file) in RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#download-requirements"><i class="fa fa-check"></i>Download requirements</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#before-we-get-started"><i class="fa fa-check"></i>Before we get started</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#data.csv"><i class="fa fa-check"></i>data.csv</a></li>
<li><a href="boxplot-and-violin-plot.html#read_csvdata.csv"><code>read_csv('data.csv')</code></a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#best-way-to-plot-data"><i class="fa fa-check"></i>Best way to plot data</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#boxplot"><i class="fa fa-check"></i><b>3.2</b> Boxplot</a>
<ul>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#what-is-a-boxplot"><i class="fa fa-check"></i>What is a boxplot?</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#boxplot-vs-bar-graph"><i class="fa fa-check"></i>Boxplot vs bar graph</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#boxplot-using-ggplot2"><i class="fa fa-check"></i>Boxplot using ggplot2</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#problem-alphabetical-order"><i class="fa fa-check"></i>Problem: Alphabetical order</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#displaying-characters-in-a-non-alphabetical-order"><i class="fa fa-check"></i>Displaying characters in a non-alphabetical order</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#double-check-if-the-day-column-is-factor"><i class="fa fa-check"></i>Double-check if the ‘Day’ column is factor</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#back-to-boxplot-using-ggplot2"><i class="fa fa-check"></i>Back to boxplot using ggplot2</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#a-boxplot-with-individual-data"><i class="fa fa-check"></i>A boxplot with individual data</a></li>
<li><a href="boxplot-and-violin-plot.html#geom_boxplot-vs-sm_boxplot"><code>geom_boxplot()</code> vs <code>sm_boxplot()</code></a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#save-boxplot"><i class="fa fa-check"></i>Save boxplot</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#violin-plot"><i class="fa fa-check"></i><b>3.3</b> Violin Plot</a>
<ul>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#structure-of-the-violin-plot"><i class="fa fa-check"></i>Structure of the violin plot</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#violin-plot-with-ggplot2"><i class="fa fa-check"></i>Violin plot with ggplot2</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#violin-plot-with-individual-points"><i class="fa fa-check"></i>Violin plot with individual points</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#geom_violin-vs-sm_violin"><i class="fa fa-check"></i>geom_violin() vs sm_violin()</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#save-your-violin-plot"><i class="fa fa-check"></i>Save your violin plot</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#summary-1"><i class="fa fa-check"></i><b>3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html"><i class="fa fa-check"></i><b>4</b> Manual and Examples of smplot</a>
<ul>
<li class="chapter" data-level="4.1" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#installation-of-the-package"><i class="fa fa-check"></i><b>4.1</b> Installation of the Package</a>
<ul>
<li><a href="manual-and-examples-of-smplot.html#what-is-smplot">What is <code>smplot</code>?</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#smplots-color-palette-and-graph-themes"><i class="fa fa-check"></i><b>4.2</b> smplot’s Color Palette and Graph Themes</a>
<ul>
<li class="chapter" data-level="" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#smplots-color-palette"><i class="fa fa-check"></i>smplot’s color palette</a></li>
<li class="chapter" data-level="" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#smplots-graph-themes"><i class="fa fa-check"></i>smplot’s graph themes</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#correlation-plot"><i class="fa fa-check"></i><b>4.3</b> Correlation Plot</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#data-frame-for-a-correlation-plot"><i class="fa fa-check"></i><b>4.3.1</b> Data frame for a correlation plot</a></li>
<li class="chapter" data-level="4.3.2" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#correlation-plot-with-both-regression-and-reference-lines"><i class="fa fa-check"></i><b>4.3.2</b> Correlation plot with both regression and reference lines</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#boxplot---sm_boxplot"><i class="fa fa-check"></i><b>4.4</b> Boxplot - <code>sm_boxplot()</code></a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#plotting-individual-points-with-unique-colors"><i class="fa fa-check"></i><b>4.4.1</b> Plotting individual points with unique colors</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#violin-plot---sm_violin"><i class="fa fa-check"></i><b>4.5</b> Violin Plot - <code>sm_violin()</code></a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#plotting-individual-points-with-unique-colors-1"><i class="fa fa-check"></i><b>4.5.1</b> Plotting individual points with unique colors</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#bar-plot---sm_bar"><i class="fa fa-check"></i><b>4.6</b> Bar Plot - <code>sm_bar()</code></a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#plotting-individual-points-with-unique-colors-2"><i class="fa fa-check"></i><b>4.6.1</b> Plotting individual points with unique colors</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#slope-chart---sm_slope"><i class="fa fa-check"></i><b>4.7</b> Slope Chart - <code>sm_slope()</code></a></li>
<li class="chapter" data-level="4.8" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#a-bland-altman-plot---sm_bland_altman"><i class="fa fa-check"></i><b>4.8</b> A Bland Altman Plot - <code>sm_bland_altman()</code></a></li>
<li class="chapter" data-level="4.9" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#raincloud-plot---sm_raincloud"><i class="fa fa-check"></i><b>4.9</b> Raincloud plot - <code>sm_raincloud()</code></a></li>
<li class="chapter" data-level="4.10" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#overriding-defaults-of-smplots-themes"><i class="fa fa-check"></i><b>4.10</b> Overriding Defaults of smplot’s Themes</a></li>
<li class="chapter" data-level="4.11" data-path="manual-and-examples-of-smplot.html"><a href="manual-and-examples-of-smplot.html#overriding-defaults-of-smplot-colors"><i class="fa fa-check"></i><b>4.11</b> Overriding Defaults of smplot Colors</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-analysis.html"><a href="data-analysis.html"><i class="fa fa-check"></i><b>5</b> Data Analysis</a>
<ul>
<li class="chapter" data-level="5.1" data-path="data-analysis.html"><a href="data-analysis.html#filter-select-and-summarise"><i class="fa fa-check"></i><b>5.1</b> <code>filter()</code>, <code>select()</code> and <code>summarise()</code></a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="data-analysis.html"><a href="data-analysis.html#filter-for-rows"><i class="fa fa-check"></i><b>5.1.1</b> <code>filter()</code> for rows</a></li>
<li class="chapter" data-level="5.1.2" data-path="data-analysis.html"><a href="data-analysis.html#select-for-columns"><i class="fa fa-check"></i><b>5.1.2</b> <code>select()</code> for columns</a></li>
<li class="chapter" data-level="5.1.3" data-path="data-analysis.html"><a href="data-analysis.html#summarise-for-grouped-summaries"><i class="fa fa-check"></i><b>5.1.3</b> <code>summarise()</code> for grouped summaries</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="data-analysis.html"><a href="data-analysis.html#plotting-average-data-with-error-bars"><i class="fa fa-check"></i><b>5.2</b> Plotting average data with error bars</a></li>
<li class="chapter" data-level="5.3" data-path="data-analysis.html"><a href="data-analysis.html#plotting-individual-data"><i class="fa fa-check"></i><b>5.3</b> Plotting Individual Data</a></li>
<li class="chapter" data-level="5.4" data-path="data-analysis.html"><a href="data-analysis.html#basic-statistics"><i class="fa fa-check"></i><b>5.4</b> Basic Statistics</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="data-analysis.html"><a href="data-analysis.html#t-test"><i class="fa fa-check"></i><b>5.4.1</b> T-test</a></li>
<li class="chapter" data-level="5.4.2" data-path="data-analysis.html"><a href="data-analysis.html#effect-size"><i class="fa fa-check"></i><b>5.4.2</b> Effect Size</a></li>
<li class="chapter" data-level="5.4.3" data-path="data-analysis.html"><a href="data-analysis.html#power-analysis"><i class="fa fa-check"></i><b>5.4.3</b> Power Analysis</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-analysis---area-under-a-curve.html"><a href="data-analysis---area-under-a-curve.html"><i class="fa fa-check"></i><b>6</b> Data Analysis - Area under a Curve</a>
<ul>
<li class="chapter" data-level="6.1" data-path="data-analysis---area-under-a-curve.html"><a href="data-analysis---area-under-a-curve.html#pipe"><i class="fa fa-check"></i><b>6.1</b> Pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="6.2" data-path="data-analysis---area-under-a-curve.html"><a href="data-analysis---area-under-a-curve.html#area-under-a-curve"><i class="fa fa-check"></i><b>6.2</b> Area under a curve</a></li>
<li class="chapter" data-level="6.3" data-path="data-analysis---area-under-a-curve.html"><a href="data-analysis---area-under-a-curve.html#reproducing-figures-in-the-paper-min-et-al.-2019"><i class="fa fa-check"></i><b>6.3</b> Reproducing figures in the paper (Min et al., 2019)</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="data-analysis---area-under-a-curve.html"><a href="data-analysis---area-under-a-curve.html#figure-3b-a-best-fit-line-with-points-and-error-bars"><i class="fa fa-check"></i><b>6.3.1</b> Figure 3B (a best-fit line with points and error bars)</a></li>
<li class="chapter" data-level="6.3.2" data-path="data-analysis---area-under-a-curve.html"><a href="data-analysis---area-under-a-curve.html#figure-3d-a-bar-graph"><i class="fa fa-check"></i><b>6.3.2</b> Figure 3D (a bar graph)</a></li>
<li class="chapter" data-level="6.3.3" data-path="data-analysis---area-under-a-curve.html"><a href="data-analysis---area-under-a-curve.html#figure-3e-modeling-in-matlab-and-plotting-in-r"><i class="fa fa-check"></i><b>6.3.3</b> Figure 3E (modeling in Matlab and plotting in R)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="basic-statistics-1.html"><a href="basic-statistics-1.html"><i class="fa fa-check"></i><b>7</b> Basic Statistics</a>
<ul>
<li class="chapter" data-level="7.1" data-path="basic-statistics-1.html"><a href="basic-statistics-1.html#one-sample-t-test"><i class="fa fa-check"></i><b>7.1</b> One-sample t-test</a></li>
<li class="chapter" data-level="7.2" data-path="basic-statistics-1.html"><a href="basic-statistics-1.html#sample-t-test"><i class="fa fa-check"></i><b>7.2</b> 2-sample t-test</a></li>
<li class="chapter" data-level="7.3" data-path="basic-statistics-1.html"><a href="basic-statistics-1.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>7.3</b> Wilcoxon Signed Rank Test</a></li>
<li class="chapter" data-level="7.4" data-path="basic-statistics-1.html"><a href="basic-statistics-1.html#effect-size-1"><i class="fa fa-check"></i><b>7.4</b> Effect Size</a></li>
<li class="chapter" data-level="7.5" data-path="basic-statistics-1.html"><a href="basic-statistics-1.html#power-analysis-1"><i class="fa fa-check"></i><b>7.5</b> Power Analysis</a></li>
<li class="chapter" data-level="7.6" data-path="basic-statistics-1.html"><a href="basic-statistics-1.html#one-way-anova"><i class="fa fa-check"></i><b>7.6</b> One-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="recreating-figures-from-front.-genetics-2021.html"><a href="recreating-figures-from-front.-genetics-2021.html"><i class="fa fa-check"></i><b>8</b> Recreating Figures from Front. Genetics (2021)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="recreating-figures-from-front.-genetics-2021.html"><a href="recreating-figures-from-front.-genetics-2021.html#figure-1---correlation-plot"><i class="fa fa-check"></i><b>8.1</b> Figure 1 - Correlation Plot</a></li>
<li class="chapter" data-level="8.2" data-path="recreating-figures-from-front.-genetics-2021.html"><a href="recreating-figures-from-front.-genetics-2021.html#figure-2---bar-plot"><i class="fa fa-check"></i><b>8.2</b> Figure 2 - Bar Plot</a></li>
<li class="chapter" data-level="8.3" data-path="recreating-figures-from-front.-genetics-2021.html"><a href="recreating-figures-from-front.-genetics-2021.html#figure-3---boxplot"><i class="fa fa-check"></i><b>8.3</b> Figure 3 - Boxplot</a></li>
<li class="chapter" data-level="8.4" data-path="recreating-figures-from-front.-genetics-2021.html"><a href="recreating-figures-from-front.-genetics-2021.html#figure-4---violin-plot"><i class="fa fa-check"></i><b>8.4</b> Figure 4 - Violin Plot</a></li>
<li class="chapter" data-level="8.5" data-path="recreating-figures-from-front.-genetics-2021.html"><a href="recreating-figures-from-front.-genetics-2021.html#figure-5---slope-chart"><i class="fa fa-check"></i><b>8.5</b> Figure 5 - Slope Chart</a></li>
<li class="chapter" data-level="8.6" data-path="recreating-figures-from-front.-genetics-2021.html"><a href="recreating-figures-from-front.-genetics-2021.html#figure-6---raincloud-plot"><i class="fa fa-check"></i><b>8.6</b> Figure 6 - Raincloud Plot</a></li>
<li class="chapter" data-level="8.7" data-path="recreating-figures-from-front.-genetics-2021.html"><a href="recreating-figures-from-front.-genetics-2021.html#figure-7---case-study"><i class="fa fa-check"></i><b>8.7</b> Figure 7 - Case Study</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis and Visualization in R Using smplot</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="basic-statistics-1" class="section level1" number="7">
<h1><span class="header-section-number">Chapter 7</span> Basic Statistics</h1>
<p>As in the previous two chapters, we will continue to use data from this paper (<a href="https://www.smin95.com/pubs/min2019.pdf">PDF</a>):</p>
<p><strong>Seung Hyun Min, Alex S. Baldwin and Robert F. Hess. Ocular dominance plasticity: A binocular combination task finds no cumulative effect with repeated patching (2019). Vision Research, 161, 36-42.</strong></p>
<p>Load the <code>tidyverse</code> and other libraries, and the csv file <code>min2019b.csv</code> using <code>read_csv()</code> from the <code>tidyverse</code> package.</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="basic-statistics-1.html#cb257-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb257-2"><a href="basic-statistics-1.html#cb257-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smplot)</span>
<span id="cb257-3"><a href="basic-statistics-1.html#cb257-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb257-4"><a href="basic-statistics-1.html#cb257-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://www.smin95.com/min2019b.csv&#39;</span>) </span>
<span id="cb257-5"><a href="basic-statistics-1.html#cb257-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   Subject   Day  Time Cbratio
##   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1 a           1     0  -0.421
## 2 b           1     0   2.82 
## 3 c           1     0   1.69 
## 4 d           1     0   2.55 
## 5 e           1     0  -0.217
## 6 f           1     0   0.626</code></pre>
<div id="one-sample-t-test" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> One-sample t-test</h2>
<p>One sample t-test compares the mean of a sample to a hypothesized mean (often 0).</p>
<p>For example, here is Figure 3E from the paper. What do the *** mean? How about ** and *? Let’s take a look.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-208-1.png" width="350.4" /></p>
<p>For instance, to determine if the area under curve (changes in contrast balance ratio over time) after patching is significant, so much so that one can confidently say that it is different from 0, we can perform a one-sample t-test using <code>t.test()</code>.</p>
<p>Let’s use data from the sampe paper. We import the data from online using <code>read_csv()</code> and store them into a variable (in this case, <code>df</code>). Then, we compute the area under a curve using <code>sm_auc_list()</code> and store the values in the variable <code>auc_df</code>.</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="basic-statistics-1.html#cb259-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://www.smin95.com/min2019b.csv&#39;</span>) </span>
<span id="cb259-2"><a href="basic-statistics-1.html#cb259-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb259-3"><a href="basic-statistics-1.html#cb259-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Day <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>Day)</span>
<span id="cb259-4"><a href="basic-statistics-1.html#cb259-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb259-5"><a href="basic-statistics-1.html#cb259-5" aria-hidden="true" tabindex="-1"></a>auc_df <span class="ot">&lt;-</span> <span class="fu">sm_auc_list</span>(<span class="at">subjects =</span> <span class="st">&#39;Subject&#39;</span>, <span class="at">conditions =</span> <span class="st">&#39;Day&#39;</span>, </span>
<span id="cb259-6"><a href="basic-statistics-1.html#cb259-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">x =</span> <span class="st">&#39;Time&#39;</span>, <span class="at">values =</span> <span class="st">&#39;Cbratio&#39;</span>,</span>
<span id="cb259-7"><a href="basic-statistics-1.html#cb259-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> df)</span>
<span id="cb259-8"><a href="basic-statistics-1.html#cb259-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb259-9"><a href="basic-statistics-1.html#cb259-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(auc_df)</span></code></pre></div>
<pre><code>##   Subject Day AUC_Cbratio
## 1       a   1    -2.36910
## 2       a   2     0.68265
## 3       a   3    -9.54795
## 4       a   4    27.12165
## 5       a   5    41.95680
## 6       b   1    60.52860</code></pre>
<p>The <code>Day</code> column of <code>df</code> has to be factored using <code>as.factor()</code> because <code>Day</code> here is a categorical, rather than, continuous variable.</p>
<p>To determine if the area under curve data on Day 1 were significantly different from 0, we could use one-sample t-test. First, let’s filter for data from only Day 1.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="basic-statistics-1.html#cb261-1" aria-hidden="true" tabindex="-1"></a>auc_df_day1 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb261-2"><a href="basic-statistics-1.html#cb261-2" aria-hidden="true" tabindex="-1"></a>auc_df_day1</span></code></pre></div>
<pre><code>##    Subject Day AUC_Cbratio
## 1        a   1    -2.36910
## 2        b   1    60.52860
## 3        c   1    94.84035
## 4        d   1   100.62510
## 5        e   1    55.32240
## 6        f   1   108.13770
## 7        g   1    63.27840
## 8        h   1    48.71625
## 9        u   1    39.11865
## 10       j   1    74.90610</code></pre>
<p>Then, lets extract the values from the <code>AUC_Cbratio</code> column and perform one-sample t-test using <code>t.test()</code>.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="basic-statistics-1.html#cb263-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  auc_df_day1$AUC_Cbratio
## t = 6.1934, df = 9, p-value = 0.0001601
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  40.82072 87.80017
## sample estimates:
## mean of x 
##  64.31045</code></pre>
<p>The p-value must be less than <strong>0.05</strong> to be considered statistically significant. It is labelled with one asterisk *. 0.001 &lt; p &lt; 0.01 corresponds to **, and p &lt; 0.001 corresponds to ***. Since the p-value reported here is less than 0.001, Figure 3E has *** for Day 1’s area under a curve.</p>
<p>We can repeat this for Days 2-5. For brevity, we repeat the example with Days 2 and 4 only.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="basic-statistics-1.html#cb265-1" aria-hidden="true" tabindex="-1"></a>auc_df_day2 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">2</span>)</span>
<span id="cb265-2"><a href="basic-statistics-1.html#cb265-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day2<span class="sc">$</span>AUC_Cbratio, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  auc_df_day2$AUC_Cbratio
## t = 3.5182, df = 9, p-value = 0.006534
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  19.60882 90.24161
## sample estimates:
## mean of x 
##  54.92521</code></pre>
<p>0.001 &lt; p &lt; 0.01 in this case, which is often denoted as **. Figure 3E shows the AUC of Day 2 with **.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="basic-statistics-1.html#cb267-1" aria-hidden="true" tabindex="-1"></a>auc_df_day4 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">4</span>)</span>
<span id="cb267-2"><a href="basic-statistics-1.html#cb267-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day4<span class="sc">$</span>AUC_Cbratio, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  auc_df_day4$AUC_Cbratio
## t = 3.0973, df = 9, p-value = 0.01278
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  11.71639 75.19169
## sample estimates:
## mean of x 
##  43.45404</code></pre>
<p>0.01 &lt; p &lt; 0.05 in this case. Therefore one asterisk * is used to label the statistical significance.</p>
</div>
<div id="sample-t-test" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> 2-sample t-test</h2>
<p>A two-sample t-test is used to compare the mean of one sample to that of another sample.</p>
<p>For example, let’s compare changes in sensory eye dominance after short-term monocular deprivation in Day 1 vs Day 5. These values are shown in the <code>Cbratio</code> column.</p>
<p>Let’s filter only for AUC data from Days 1 and 5.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="basic-statistics-1.html#cb269-1" aria-hidden="true" tabindex="-1"></a>auc_df_day1 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb269-2"><a href="basic-statistics-1.html#cb269-2" aria-hidden="true" tabindex="-1"></a>auc_df_day5 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">5</span>)</span>
<span id="cb269-3"><a href="basic-statistics-1.html#cb269-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb269-4"><a href="basic-statistics-1.html#cb269-4" aria-hidden="true" tabindex="-1"></a>auc_df_day15 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> Day <span class="sc">==</span> <span class="dv">5</span>)</span></code></pre></div>
<p>Now, let’s plot a bar graph to display the AUC from Days 1 and 5 using <code>sm_bar()</code>.</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="basic-statistics-1.html#cb270-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> auc_df_day15, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Day, <span class="at">y =</span> AUC_Cbratio, <span class="at">fill =</span> Day)) <span class="sc">+</span></span>
<span id="cb270-2"><a href="basic-statistics-1.html#cb270-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sm_bar</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">color =</span> <span class="st">&#39;white&#39;</span>, <span class="at">bar_fill_color =</span> <span class="st">&#39;gray80&#39;</span>) <span class="sc">+</span></span>
<span id="cb270-3"><a href="basic-statistics-1.html#cb270-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">sm_palette</span>(<span class="dv">2</span>)) <span class="sc">+</span></span>
<span id="cb270-4"><a href="basic-statistics-1.html#cb270-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&#39;AUC in Days 1 and 5&#39;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-215-1.png" width="355.2" /></p>
<p>There seems to be a difference in the AUC <code>AUC_Cbratio</code> between Days 1 and 5. The error bars (in this case, standard error) are barely overlapping. If the error bars are clearly overlapping, there is often no significant difference (p &lt; 0.05) between the two data sets. If there is no overlap, it is highly likely that a statistical test will show a significant difference (p &lt; 0.05). Let’s take a look using <strong>t-test</strong> using the function <code>t.test()</code>.</p>
<p><code>t.test()</code> allows us to compare whether data between two different groups are significantly different. Here, <code>$</code> is used to <strong>extract</strong> data from a specific column within a data frame. You could type <code>df_0min$</code>, press the <strong>Tab</strong> button from the keyboard, and see what happens. Since we will only compare values in the <code>AUC_Cbratio</code> column, let’s select for the <code>AUC_Cbratio</code> column and use these values in our <code>t.test()</code>.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="basic-statistics-1.html#cb271-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, auc_df_day5<span class="sc">$</span>AUC_Cbratio, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  auc_df_day1$AUC_Cbratio and auc_df_day5$AUC_Cbratio
## t = 1.5694, df = 9, p-value = 0.151
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -10.17563  56.27723
## sample estimates:
## mean of the differences 
##                 23.0508</code></pre>
<p>In this case, the subjects are <strong>paired</strong> because the 10 subjects performed on both Days 1 and 5. If your data are not paired (ex. patients vs controls) and you want to perform a t-test, you can set <code>paired = FALSE</code>.</p>
<p>If we are reporting the results, we should report it as such, t(9) = 1.60, p = 0.15. The difference between Days 1 and 5 is not statistically significant.</p>
<p>T-test can only be used when the data assume normality. In other word, the data that are to be analyzed using <code>t.test()</code> must have a normal distribution (shown below).</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-217-1.png" width="355.2" /></p>
<p>Whether the data have a normal distribution can be checked using a Shaprio-Wilk test (<code>shapiro.test()</code>). If p &gt; 0.05, then the data have a normal distribution, and therefore, t-test can be used to analyze the data. If p &lt; 0.05, the data are not normally distributed, and t-test cannot be used.</p>
<p>For example, let’s check whether the AUC data from Day 1 have a normal distribution.</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="basic-statistics-1.html#cb273-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  auc_df_day1$AUC_Cbratio
## W = 0.95039, p-value = 0.6732</code></pre>
<p>P value is 0.67, which is larger than 0.05. Therefore, the AUCs from Day 1 have a normal distribution.</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="basic-statistics-1.html#cb275-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(auc_df_day5<span class="sc">$</span>AUC_Cbratio)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  auc_df_day5$AUC_Cbratio
## W = 0.97531, p-value = 0.9353</code></pre>
<p>P value is 0.935, which is larger than 0.05. Therefore, the AUCs from Day 5 have a normal distribution. More information about <code>shapiro.test()</code> can be found in this link: <a href="http://www.sthda.com/english/wiki/normality-test-in-r" class="uri">http://www.sthda.com/english/wiki/normality-test-in-r</a>.</p>
<p>T-test is a type of <strong>parametric</strong> statistical test, which is used to analyze data that are normally distributed. If the data are not normally distributed, <strong>non-parametric</strong> statistical test can be used.</p>
</div>
<div id="wilcoxon-signed-rank-test" class="section level2" number="7.3">
<h2><span class="header-section-number">7.3</span> Wilcoxon Signed Rank Test</h2>
<p>Wilcoxon Signed Rank Test is a <strong>non-parametric</strong> statistical test that is used instead of a t-test when the data are <strong>not normally distributed</strong>.</p>
<p>If we assume that the Shaprio-Wilk test yields p &lt; 0.05 for the following datasets, necessitating us to use a Wilcoxon Signed Rank Test for both one-sample and two-sample tests.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="basic-statistics-1.html#cb277-1" aria-hidden="true" tabindex="-1"></a><span class="co"># one-sample Wilcoxon Signed Rank Test</span></span>
<span id="cb277-2"><a href="basic-statistics-1.html#cb277-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  auc_df_day1$AUC_Cbratio
## V = 54, p-value = 0.003906
## alternative hypothesis: true location is not equal to 0</code></pre>
<p>The p-value is 0.0039, which is less than 0.05. Therefore, according to the Wilcoxon test, the AUCs from Day 1 are significantly different from 0.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="basic-statistics-1.html#cb279-1" aria-hidden="true" tabindex="-1"></a><span class="co"># two-sample Wilcoxon test</span></span>
<span id="cb279-2"><a href="basic-statistics-1.html#cb279-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, auc_df_day5<span class="sc">$</span>AUC_Cbratio, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  auc_df_day1$AUC_Cbratio and auc_df_day5$AUC_Cbratio
## V = 43, p-value = 0.1309
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>The p-value is 0.13, which is larger than 0.05. Therefore, according to the Wilcoxon test, the AUCs from Days 1 and 2 are not significantly different.</p>
</div>
<div id="effect-size-1" class="section level2" number="7.4">
<h2><span class="header-section-number">7.4</span> Effect Size</h2>
<p>However, even if p-value is larger than 0.05, this does not mean that there is no significant difference between the two groups/conditions. In fact, even a strong drug effect in a study that compares placebo vs. drug can result in p &gt; 0.05 if the sample size is too small.</p>
<p>On the other hand, if a study is conducted a very large sample size (1000 patients per group) to examine the effect of a very weak drug, the data between weak drug and control can give us a p &lt; 0.05, which indicates a statistically significant difference.</p>
<p>In short, <strong>p-value is not everything because it depends on the sample size.</strong></p>
<p>If the sample size is small, p-value can be larger than 0.05. But as the sample gets larger, p-value will decrease even if the mean difference between the two groups remains the same.</p>
<p>In this example, the sample size is not large (n=10). Therefore, one might ask whether our conclusion that there is no significant difference between Days 1 and 5 is truly valid. One might also believe that if our sample size was larger (ex. n=50), we would have found a significant difference between Days 1 and 5.</p>
<p>To respond to this concern, we might need to calculate the <strong>effect size</strong>. If the effect size is large, there is a large difference between the sample groups. <strong>Unlike the p-value, the effect size does not depend on the sample size.</strong></p>
<p>One measure to capture the effect size is <strong>Cohen’s d</strong>. We can use <code>sm_effsize()</code> to calculate Cohen’s d as a measure for the effect size.</p>
<ul>
<li><strong>Small</strong> effect size: Cohen’s d around <strong>0.2</strong></li>
<li><strong>Medium</strong> effect size: Cohen’s d around <strong>0.5</strong></li>
<li><strong>Large</strong> effect size: Cohen’s d &gt; <strong>0.8</strong>.</li>
</ul>
<p>The inputs for <code>sm_effsize()</code> are the data of two sample groups, just as they were in <code>t.test()</code>.</p>
<p>Let’s compute the effect size (Cohen’s d) using AUC data from Days 1 and 2.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="basic-statistics-1.html#cb281-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sm_effsize</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, auc_df_day2<span class="sc">$</span>AUC_Cbratio)</span></code></pre></div>
<pre><code>## [1] 0.2238542</code></pre>
<p>Cohen’s d equals <strong>0.224</strong>, which is a very small effect size. This indicates that there is a very small difference in AUC between Days 1 and 2.</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="basic-statistics-1.html#cb283-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, auc_df_day2<span class="sc">$</span>AUC_Cbratio,</span>
<span id="cb283-2"><a href="basic-statistics-1.html#cb283-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  auc_df_day1$AUC_Cbratio and auc_df_day2$AUC_Cbratio
## t = 0.46312, df = 9, p-value = 0.6543
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -36.45777  55.22823
## sample estimates:
## mean of the differences 
##                 9.38523</code></pre>
<p>Also, it is recommended that <strong>both p-value and effect size are reported</strong> at all times. In this example, I would report the results as: <strong>t(9) = 0.46, p = 0.65, Cohen’s d = 0.22</strong>.</p>
<p>Let’s see what happens in the effect size and p-value from t-test if there are 1000 subjects.</p>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="basic-statistics-1.html#cb285-1" aria-hidden="true" tabindex="-1"></a>auc_df_day1b <span class="ot">&lt;-</span> <span class="fu">do.call</span>(<span class="st">&#39;rbind&#39;</span>, <span class="fu">replicate</span>(<span class="dv">100</span>, auc_df_day1, <span class="at">simplify =</span> <span class="cn">FALSE</span>))</span>
<span id="cb285-2"><a href="basic-statistics-1.html#cb285-2" aria-hidden="true" tabindex="-1"></a>auc_df_day1b<span class="sc">$</span>Subject <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&#39;S&#39;</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>)</span>
<span id="cb285-3"><a href="basic-statistics-1.html#cb285-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(auc_df_day1b, <span class="dv">30</span>)</span></code></pre></div>
<pre><code>##    Subject Day AUC_Cbratio
## 1       S1   1    -2.36910
## 2       S2   1    60.52860
## 3       S3   1    94.84035
## 4       S4   1   100.62510
## 5       S5   1    55.32240
## 6       S6   1   108.13770
## 7       S7   1    63.27840
## 8       S8   1    48.71625
## 9       S9   1    39.11865
## 10     S10   1    74.90610
## 11     S11   1    -2.36910
## 12     S12   1    60.52860
## 13     S13   1    94.84035
## 14     S14   1   100.62510
## 15     S15   1    55.32240
## 16     S16   1   108.13770
## 17     S17   1    63.27840
## 18     S18   1    48.71625
## 19     S19   1    39.11865
## 20     S20   1    74.90610
## 21     S21   1    -2.36910
## 22     S22   1    60.52860
## 23     S23   1    94.84035
## 24     S24   1   100.62510
## 25     S25   1    55.32240
## 26     S26   1   108.13770
## 27     S27   1    63.27840
## 28     S28   1    48.71625
## 29     S29   1    39.11865
## 30     S30   1    74.90610</code></pre>
<p>We have replicated all the rows of the data frame <code>auc_df_day1</code> by 100 times to create 1000 rows total (i.e., 1000 subjects).</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="basic-statistics-1.html#cb287-1" aria-hidden="true" tabindex="-1"></a>auc_df_day2b <span class="ot">&lt;-</span> <span class="fu">do.call</span>(<span class="st">&#39;rbind&#39;</span>, <span class="fu">replicate</span>(<span class="dv">100</span>, auc_df_day2, <span class="at">simplify =</span> <span class="cn">FALSE</span>))</span>
<span id="cb287-2"><a href="basic-statistics-1.html#cb287-2" aria-hidden="true" tabindex="-1"></a>auc_df_day2b<span class="sc">$</span>Subject <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&#39;S&#39;</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>)</span>
<span id="cb287-3"><a href="basic-statistics-1.html#cb287-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(auc_df_day2b, <span class="dv">30</span>)</span></code></pre></div>
<pre><code>##    Subject Day AUC_Cbratio
## 1       S1   2     0.68265
## 2       S2   2    80.38215
## 3       S3   2     1.78695
## 4       S4   2   -19.60125
## 5       S5   2   132.99825
## 6       S6   2    31.14285
## 7       S7   2    80.24685
## 8       S8   2    75.98130
## 9       S9   2    64.56690
## 10     S10   2   101.06550
## 11     S11   2     0.68265
## 12     S12   2    80.38215
## 13     S13   2     1.78695
## 14     S14   2   -19.60125
## 15     S15   2   132.99825
## 16     S16   2    31.14285
## 17     S17   2    80.24685
## 18     S18   2    75.98130
## 19     S19   2    64.56690
## 20     S20   2   101.06550
## 21     S21   2     0.68265
## 22     S22   2    80.38215
## 23     S23   2     1.78695
## 24     S24   2   -19.60125
## 25     S25   2   132.99825
## 26     S26   2    31.14285
## 27     S27   2    80.24685
## 28     S28   2    75.98130
## 29     S29   2    64.56690
## 30     S30   2   101.06550</code></pre>
<p>We have replicated all the rows of the data frame <code>auc_df_day2</code> by 100 times to create 1000 rows total (i.e., 1000 subjects).</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="basic-statistics-1.html#cb289-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sm_effsize</span>(auc_df_day1b<span class="sc">$</span>AUC_Cbratio, auc_df_day2b<span class="sc">$</span>AUC_Cbratio)</span></code></pre></div>
<pre><code>## [1] 0.2358451</code></pre>
<p>The effect size is 0.24. It has barely changed. Theoretically, it should <strong>not</strong> change (i.e., stay at 0.224), but for some reason here, it has changed very slightly.</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="basic-statistics-1.html#cb291-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day1b<span class="sc">$</span>AUC_Cbratio, auc_df_day2b<span class="sc">$</span>AUC_Cbratio,</span>
<span id="cb291-2"><a href="basic-statistics-1.html#cb291-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  auc_df_day1b$AUC_Cbratio and auc_df_day2b$AUC_Cbratio
## t = 4.8793, df = 999, p-value = 1.239e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   5.610696 13.159764
## sample estimates:
## mean of the differences 
##                 9.38523</code></pre>
<p>Now, the p-value is <strong>much less than 0.001</strong>, rather than staying at 0.65. Therefore, we can now observe that p-value is heavily affected by the sample size, whereas the effect size (Cohen’s d) does not. In short, as the sample size increases, the p-value decreases even if the effect size stays the same.</p>
</div>
<div id="power-analysis-1" class="section level2" number="7.5">
<h2><span class="header-section-number">7.5</span> Power Analysis</h2>
<p>We got p &gt; 0.05 with our small sample size (n = 10). As we previously mentioned, we know that p-value gets smaller with an increasing sample size. <strong>Therefore, given the mean difference between two sample groups (i.e., same effect size), the p-value can change depending on the sample size</strong>. So, it is important to report both the p-value and the effect size.</p>
<p>So, one might be concerned with what would be the minimal sample size to detect a statistically significant difference between the two groups (Days 1 and 5). This can be achieved using <strong>power analysis</strong>. Note that p can always be less than 0.05 as long as the sample size meets the requirement (i.e., very large).</p>
<p>If the effect size was large but the data yielded p &gt; 0.05, then we could predict that the minimal sample size from power analysis would be not large. If the effect size was small and the data yielded p &gt; 0.05, as it was for my data, the minimal sample size to yield p &lt; 0.05 would need to be very large.</p>
<p>If the minimal sample size from power analysis was not large (hence, large effect size), then one could conclude that I did not collect enough data and incorrectly concluded that there was no significant difference between the two groups. This would be so because if the sample size was larger, I would have gotten p &lt; 0.05.</p>
<p><strong>Power analysis</strong> can be performed using <code>sm_power()</code>. The inputs for <code>sm_power()</code> are data of two sample groups, just as they were in <code>t.test()</code>.</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="basic-statistics-1.html#cb293-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sm_power</span>(auc_df_day1b<span class="sc">$</span>AUC_Cbratio, auc_df_day2b<span class="sc">$</span>AUC_Cbratio,</span>
<span id="cb293-2"><a href="basic-statistics-1.html#cb293-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##      Paired t test power calculation 
## 
##               n = 143.0411
##               d = 0.2358451
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number of *pairs*</code></pre>
<p>According to our power analysis (significant level = 0.05, power = 80%), we would need about <strong>143 subjects</strong> per group (<code>n = 143.0411</code>) for the p-value to reach below 0.05 and, therefore, for us to detect a statistically significant difference in AUCs between Days 1 and 2. In other words, the difference between Days 1 and 2 is very small. Also, the conclusion that there was no difference between the days seems to be valid even though the sample size is small.</p>
<p>To learn more about performing statistical tests in R, please check out the book entitled <strong>YaRrr! The Pirate’s Guide to R</strong> by Nathaniel Phillips (<a href="https://bookdown.org/ndphillips/YaRrr/" class="uri">https://bookdown.org/ndphillips/YaRrr/</a>).</p>
</div>
<div id="one-way-anova" class="section level2" number="7.6">
<h2><span class="header-section-number">7.6</span> One-way ANOVA</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-analysis---area-under-a-curve.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="recreating-figures-from-front.-genetics-2021.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/smin95/dataviz/edit/master/07-statistics.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/smin95/dataviz/blob/master/07-statistics.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
