<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Basic Statistics | Data Analysis and Visualization in R Using smplot2</title>
  <meta name="description" content="Chapter 10 Basic Statistics | Data Analysis and Visualization in R Using smplot2" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Basic Statistics | Data Analysis and Visualization in R Using smplot2" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Basic Statistics | Data Analysis and Visualization in R Using smplot2" />
  
  
  

<meta name="author" content="Seung Hyun Min" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="calculating-linear-slopes.html"/>
<link rel="next" href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Dataviz with smplot2</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome!</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#major-updates"><i class="fa fa-check"></i>Major updates</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#ggplot2-version"><i class="fa fa-check"></i>ggplot2 version</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#issues-and-contact"><i class="fa fa-check"></i>Issues and contact</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#about-the-author"><i class="fa fa-check"></i>About the author</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="opening-remarks.html"><a href="opening-remarks.html"><i class="fa fa-check"></i><b>1</b> Opening Remarks</a>
<ul>
<li class="chapter" data-level="1.1" data-path="opening-remarks.html"><a href="opening-remarks.html#how-to-read-this-book"><i class="fa fa-check"></i><b>1.1</b> How to read this book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html"><i class="fa fa-check"></i><b>2</b> Download RStudio &amp; Basics of R</a>
<ul>
<li class="chapter" data-level="2.1" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#setting-up-rstudio"><i class="fa fa-check"></i><b>2.1</b> Setting up RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#why-use-r-for-data-visualization"><i class="fa fa-check"></i>Why use R for data visualization?</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#other-available-resources-for-r"><i class="fa fa-check"></i>Other available resources for R</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#download-requirements-for-rstudio"><i class="fa fa-check"></i>Download requirements for RStudio</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#open-rstudio"><i class="fa fa-check"></i>Open RStudio</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#lets-make-a-folder-and-set-it-as-working-directory"><i class="fa fa-check"></i>Let’s make a folder and set it as working directory</a></li>
<li class="chapter" data-level="2.1.1" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#how-to-run-your-code"><i class="fa fa-check"></i><b>2.1.1</b> How to run your code</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#basics-of-r"><i class="fa fa-check"></i><b>2.2</b> Basics of R</a>
<ul>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#lets-type-some-codes"><i class="fa fa-check"></i>Let’s type some codes</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#how-can-i-learn-most-effectively-with-the-notes"><i class="fa fa-check"></i>How can I learn most effectively with the notes?</a></li>
<li class="chapter" data-level="" data-path="download-rstudio-basics-of-r.html"><a href="download-rstudio-basics-of-r.html#more-installation"><i class="fa fa-check"></i>More installation</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Data Visualization with smplot2</b></span></li>
<li class="chapter" data-level="3" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html"><i class="fa fa-check"></i><b>3</b> Basics of ggplot2 and Correlation Plot</a>
<ul>
<li class="chapter" data-level="3.1" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#uploading-data"><i class="fa fa-check"></i><b>3.1</b> Uploading data</a>
<ul>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#sample-data-mpg"><i class="fa fa-check"></i>Sample data: mpg</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#basics-of-ggplot2"><i class="fa fa-check"></i><b>3.2</b> Basics of ggplot2</a>
<ul>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#lets-make-some-graphs"><i class="fa fa-check"></i>Let’s make some graphs</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#how-ggplot-works"><i class="fa fa-check"></i>How ggplot works</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#different-color-of-points-for-each-unique-group"><i class="fa fa-check"></i>Different color of points for each unique group</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#different-color-shape-for-each-group"><i class="fa fa-check"></i>Different color &amp; shape for each group</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#same-shape-across-all-groups"><i class="fa fa-check"></i>Same shape across all groups</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#how-do-we-draw-the-best-fit-line-of-the-graph"><i class="fa fa-check"></i>How do we draw the best-fit line of the graph?</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#geom_point-geom_smooth"><i class="fa fa-check"></i>geom_point() + geom_smooth()</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#writing-shorter-codes"><i class="fa fa-check"></i>Writing shorter codes</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#improve-data-visualization-using-smplot2"><i class="fa fa-check"></i><b>3.3</b> Improve data visualization using smplot2</a>
<ul>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#positive-relationship-between-x--and-y-axes"><i class="fa fa-check"></i>Positive relationship between x- and y-axes</a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#reporting-statistics-from-a-paired-correlation"><i class="fa fa-check"></i>Reporting statistics from a paired correlation</a></li>
<li class="chapter" data-level="3.3.1" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#changing-the-text"><i class="fa fa-check"></i><b>3.3.1</b> Changing the text</a></li>
<li class="chapter" data-level="3.3.2" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#plotting-the-average-with-standard-errors"><i class="fa fa-check"></i><b>3.3.2</b> Plotting the average with standard errors</a></li>
<li><a href="basics-of-ggplot2-and-correlation-plot.html#fill-0f993d-vs-fill-green"><code>fill = '#0f993d'</code> vs <code>fill = 'green'</code></a></li>
<li class="chapter" data-level="" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#different-color-for-each-group-but-with-other-colors"><i class="fa fa-check"></i>Different color for each group but with other colors</a></li>
<li><a href="basics-of-ggplot2-and-correlation-plot.html#lets-save-the-plot-as-an-image-in-your-folder-learnr-by-using-the-variable-figure1.">Let’s save the plot as an image in your folder <strong>LearnR</strong> by using the variable <strong>figure1</strong>.</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="basics-of-ggplot2-and-correlation-plot.html"><a href="basics-of-ggplot2-and-correlation-plot.html#summary"><i class="fa fa-check"></i><b>3.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html"><i class="fa fa-check"></i><b>4</b> Boxplot and Violin Plot</a>
<ul>
<li class="chapter" data-level="4.1" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#upload-sample-data-csv-file-in-rstudio"><i class="fa fa-check"></i><b>4.1</b> Upload sample data (csv file) in RStudio</a>
<ul>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#download-requirements"><i class="fa fa-check"></i>Download requirements</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#before-we-get-started"><i class="fa fa-check"></i>Before we get started</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#data.csv"><i class="fa fa-check"></i>data.csv</a></li>
<li><a href="boxplot-and-violin-plot.html#read_csvdata.csv"><code>read_csv('data.csv')</code></a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#best-way-to-plot-data"><i class="fa fa-check"></i>Best way to plot data</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#boxplot"><i class="fa fa-check"></i><b>4.2</b> Boxplot</a>
<ul>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#what-is-a-boxplot"><i class="fa fa-check"></i>What is a boxplot?</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#boxplot-vs-bar-graph"><i class="fa fa-check"></i>Boxplot vs bar graph</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#boxplot-using-ggplot2"><i class="fa fa-check"></i>Boxplot using ggplot2</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#problem-alphabetical-order"><i class="fa fa-check"></i>Problem: Alphabetical order</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#displaying-characters-in-a-non-alphabetical-order"><i class="fa fa-check"></i>Displaying characters in a non-alphabetical order</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#double-check-if-the-day-column-is-factor"><i class="fa fa-check"></i>Double-check if the ‘Day’ column is factor</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#back-to-boxplot-using-ggplot2"><i class="fa fa-check"></i>Back to boxplot using ggplot2</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#a-boxplot-with-individual-data"><i class="fa fa-check"></i>A boxplot with individual data</a></li>
<li><a href="boxplot-and-violin-plot.html#geom_boxplot-vs-sm_boxplot"><code>geom_boxplot()</code> vs <code>sm_boxplot()</code></a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#save-boxplot"><i class="fa fa-check"></i>Save boxplot</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#violin-plot"><i class="fa fa-check"></i><b>4.3</b> Violin Plot</a>
<ul>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#structure-of-the-violin-plot"><i class="fa fa-check"></i>Structure of the violin plot</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#violin-plot-with-ggplot2"><i class="fa fa-check"></i>Violin plot with ggplot2</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#violin-plot-with-individual-points"><i class="fa fa-check"></i>Violin plot with individual points</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#geom_violin-vs-sm_violin"><i class="fa fa-check"></i>geom_violin() vs sm_violin()</a></li>
<li class="chapter" data-level="" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#save-your-violin-plot"><i class="fa fa-check"></i>Save your violin plot</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="boxplot-and-violin-plot.html"><a href="boxplot-and-violin-plot.html#summary-1"><i class="fa fa-check"></i><b>4.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html"><i class="fa fa-check"></i><b>5</b> Bar Graph, Slope Chart and Point plot</a>
<ul>
<li class="chapter" data-level="5.1" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#bar-graph"><i class="fa fa-check"></i><b>5.1</b> Bar graph</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#scaling-the-y-axis"><i class="fa fa-check"></i><b>5.1.1</b> Scaling the y-axis</a></li>
<li class="chapter" data-level="5.1.2" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#plotting-individual-points-with-unique-colors"><i class="fa fa-check"></i><b>5.1.2</b> Plotting individual points with unique colors</a></li>
<li class="chapter" data-level="5.1.3" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#other-parameters"><i class="fa fa-check"></i><b>5.1.3</b> Other parameters</a></li>
<li class="chapter" data-level="5.1.4" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#bar-graph-with-data-of-multiple-groups"><i class="fa fa-check"></i><b>5.1.4</b> Bar graph with data of multiple groups</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#slope-chart"><i class="fa fa-check"></i><b>5.2</b> Slope chart</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#slope-chart-with-mean-plot"><i class="fa fa-check"></i><b>5.2.1</b> Slope chart with mean plot</a></li>
<li class="chapter" data-level="5.2.2" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#slope-chart-with-mean-plot-and-error-bar"><i class="fa fa-check"></i><b>5.2.2</b> Slope chart with mean plot and error bar</a></li>
<li class="chapter" data-level="5.2.3" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#slope-chart-with-multiple-x-levels"><i class="fa fa-check"></i><b>5.2.3</b> Slope chart with multiple x levels</a></li>
<li class="chapter" data-level="5.2.4" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#slope-chart-with-multiple-groups-and-x-levels"><i class="fa fa-check"></i><b>5.2.4</b> Slope chart with multiple groups and x levels</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#point-plot"><i class="fa fa-check"></i><b>5.3</b> Point plot</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#data-with-more-than-two-groups"><i class="fa fa-check"></i><b>5.3.1</b> Data with more than two groups</a></li>
<li class="chapter" data-level="5.3.2" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#point-plot-with-a-shadow-using-data-of-one-group"><i class="fa fa-check"></i><b>5.3.2</b> Point plot with a shadow using data of one group</a></li>
<li class="chapter" data-level="5.3.3" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#point-plot-with-a-shadow-using-data-of-multiple-groups"><i class="fa fa-check"></i><b>5.3.3</b> Point plot with a shadow using data of multiple groups</a></li>
<li class="chapter" data-level="5.3.4" data-path="bar-graph-slope-chart-and-point-plot.html"><a href="bar-graph-slope-chart-and-point-plot.html#adding-and-modifying-legends"><i class="fa fa-check"></i><b>5.3.4</b> Adding and modifying legends</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="raincloud-and-forest-plots.html"><a href="raincloud-and-forest-plots.html"><i class="fa fa-check"></i><b>6</b> Raincloud and Forest Plots</a>
<ul>
<li class="chapter" data-level="6.1" data-path="raincloud-and-forest-plots.html"><a href="raincloud-and-forest-plots.html#raincloud-plot"><i class="fa fa-check"></i><b>6.1</b> Raincloud plot</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="raincloud-and-forest-plots.html"><a href="raincloud-and-forest-plots.html#changing-the-x-axis-labels"><i class="fa fa-check"></i><b>6.1.1</b> Changing the x-axis labels</a></li>
<li class="chapter" data-level="6.1.2" data-path="raincloud-and-forest-plots.html"><a href="raincloud-and-forest-plots.html#separating-the-components-and-configuration"><i class="fa fa-check"></i><b>6.1.2</b> Separating the components and configuration</a></li>
<li class="chapter" data-level="6.1.3" data-path="raincloud-and-forest-plots.html"><a href="raincloud-and-forest-plots.html#changng-the-theme-and-orientation"><i class="fa fa-check"></i><b>6.1.3</b> Changng the theme and orientation</a></li>
<li class="chapter" data-level="6.1.4" data-path="raincloud-and-forest-plots.html"><a href="raincloud-and-forest-plots.html#raincloud-plot-with-data-from-multiple-groups"><i class="fa fa-check"></i><b>6.1.4</b> Raincloud plot with data from multiple groups</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="raincloud-and-forest-plots.html"><a href="raincloud-and-forest-plots.html#forest-plot"><i class="fa fa-check"></i><b>6.2</b> Forest plot</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="raincloud-and-forest-plots.html"><a href="raincloud-and-forest-plots.html#plotting-the-forest-plot-using-data-of-multiple-groups"><i class="fa fa-check"></i><b>6.2.1</b> Plotting the forest plot using data of multiple groups</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Data Analysis with smplot2</b></span></li>
<li class="chapter" data-level="7" data-path="combining-plots-with-common-axes.html"><a href="combining-plots-with-common-axes.html"><i class="fa fa-check"></i><b>7</b> Combining Plots with Common Axes</a>
<ul>
<li class="chapter" data-level="7.1" data-path="combining-plots-with-common-axes.html"><a href="combining-plots-with-common-axes.html#filter-select-and-summarise"><i class="fa fa-check"></i><b>7.1</b> <code>filter()</code>, <code>select()</code> and <code>summarise()</code></a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="combining-plots-with-common-axes.html"><a href="combining-plots-with-common-axes.html#filter-for-rows"><i class="fa fa-check"></i><b>7.1.1</b> <code>filter()</code> for rows</a></li>
<li class="chapter" data-level="7.1.2" data-path="combining-plots-with-common-axes.html"><a href="combining-plots-with-common-axes.html#select-for-columns"><i class="fa fa-check"></i><b>7.1.2</b> <code>select()</code> for columns</a></li>
<li class="chapter" data-level="7.1.3" data-path="combining-plots-with-common-axes.html"><a href="combining-plots-with-common-axes.html#summarise-for-grouped-summaries"><i class="fa fa-check"></i><b>7.1.3</b> <code>summarise()</code> for grouped summaries</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="combining-plots-with-common-axes.html"><a href="combining-plots-with-common-axes.html#plotting-the-averaged-data-with-error-bars"><i class="fa fa-check"></i><b>7.2</b> Plotting the averaged data with error bars</a></li>
<li class="chapter" data-level="7.3" data-path="combining-plots-with-common-axes.html"><a href="combining-plots-with-common-axes.html#plotting-individual-data"><i class="fa fa-check"></i><b>7.3</b> Plotting individual data</a></li>
<li class="chapter" data-level="7.4" data-path="combining-plots-with-common-axes.html"><a href="combining-plots-with-common-axes.html#putting-multiple-plots-together"><i class="fa fa-check"></i><b>7.4</b> Putting multiple plots together</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="calculating-area-under-a-curve.html"><a href="calculating-area-under-a-curve.html"><i class="fa fa-check"></i><b>8</b> Calculating Area under a Curve</a>
<ul>
<li class="chapter" data-level="8.1" data-path="calculating-area-under-a-curve.html"><a href="calculating-area-under-a-curve.html#pipe"><i class="fa fa-check"></i><b>8.1</b> Pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="8.2" data-path="calculating-area-under-a-curve.html"><a href="calculating-area-under-a-curve.html#area-under-a-curve"><i class="fa fa-check"></i><b>8.2</b> Area under a curve</a></li>
<li class="chapter" data-level="8.3" data-path="calculating-area-under-a-curve.html"><a href="calculating-area-under-a-curve.html#reproducing-figures-in-the-paper-min-et-al.-2019"><i class="fa fa-check"></i><b>8.3</b> Reproducing figures in the paper (Min et al., 2019)</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="calculating-area-under-a-curve.html"><a href="calculating-area-under-a-curve.html#figure-3b-a-best-fit-line-with-points-and-error-bars"><i class="fa fa-check"></i><b>8.3.1</b> Figure 3B (a best-fit line with points and error bars)</a></li>
<li class="chapter" data-level="8.3.2" data-path="calculating-area-under-a-curve.html"><a href="calculating-area-under-a-curve.html#figure-3d-a-bar-graph"><i class="fa fa-check"></i><b>8.3.2</b> Figure 3D (a bar graph)</a></li>
<li class="chapter" data-level="8.3.3" data-path="calculating-area-under-a-curve.html"><a href="calculating-area-under-a-curve.html#figure-3e-modeling-in-matlab-and-plotting-in-r"><i class="fa fa-check"></i><b>8.3.3</b> Figure 3E (modeling in Matlab and plotting in R)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="calculating-linear-slopes.html"><a href="calculating-linear-slopes.html"><i class="fa fa-check"></i><b>9</b> Calculating Linear Slopes</a>
<ul>
<li class="chapter" data-level="9.1" data-path="calculating-linear-slopes.html"><a href="calculating-linear-slopes.html#linear-relationship-using-lm"><i class="fa fa-check"></i><b>9.1</b> Linear relationship using <code>lm()</code></a></li>
<li class="chapter" data-level="9.2" data-path="calculating-linear-slopes.html"><a href="calculating-linear-slopes.html#calculating-slopes-of-all-subjects-groups-and-conditions"><i class="fa fa-check"></i><b>9.2</b> Calculating slopes of all subjects, groups and conditions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="basic-statistics.html"><a href="basic-statistics.html"><i class="fa fa-check"></i><b>10</b> Basic Statistics</a>
<ul>
<li class="chapter" data-level="10.1" data-path="basic-statistics.html"><a href="basic-statistics.html#one-sample-t-test"><i class="fa fa-check"></i><b>10.1</b> One-sample t-test</a></li>
<li class="chapter" data-level="10.2" data-path="basic-statistics.html"><a href="basic-statistics.html#two-sample-t-test"><i class="fa fa-check"></i><b>10.2</b> Two-sample t-test</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="basic-statistics.html"><a href="basic-statistics.html#shapiro-wilk-test-to-test-for-normality-of-data"><i class="fa fa-check"></i><b>10.2.1</b> Shapiro-Wilk Test to test for Normality of Data</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="basic-statistics.html"><a href="basic-statistics.html#wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>10.3</b> Wilcoxon Signed-rank Test</a></li>
<li class="chapter" data-level="10.4" data-path="basic-statistics.html"><a href="basic-statistics.html#effect-size"><i class="fa fa-check"></i><b>10.4</b> Effect Size</a></li>
<li class="chapter" data-level="10.5" data-path="basic-statistics.html"><a href="basic-statistics.html#power-analysis"><i class="fa fa-check"></i><b>10.5</b> Power Analysis</a></li>
<li class="chapter" data-level="10.6" data-path="basic-statistics.html"><a href="basic-statistics.html#one-way-anova"><i class="fa fa-check"></i><b>10.6</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="10.6.1" data-path="basic-statistics.html"><a href="basic-statistics.html#check-for-outliers"><i class="fa fa-check"></i><b>10.6.1</b> Check for Outliers</a></li>
<li class="chapter" data-level="10.6.2" data-path="basic-statistics.html"><a href="basic-statistics.html#checking-for-normality-of-data"><i class="fa fa-check"></i><b>10.6.2</b> Checking for Normality of Data</a></li>
<li class="chapter" data-level="10.6.3" data-path="basic-statistics.html"><a href="basic-statistics.html#checking-the-assumption-for-homogeneity-of-variance"><i class="fa fa-check"></i><b>10.6.3</b> Checking the Assumption for Homogeneity of Variance</a></li>
<li class="chapter" data-level="10.6.4" data-path="basic-statistics.html"><a href="basic-statistics.html#computing-one-way-anova"><i class="fa fa-check"></i><b>10.6.4</b> Computing One-way ANOVA</a></li>
<li class="chapter" data-level="10.6.5" data-path="basic-statistics.html"><a href="basic-statistics.html#post-hoc-tests"><i class="fa fa-check"></i><b>10.6.5</b> Post-hoc Tests</a></li>
<li class="chapter" data-level="10.6.6" data-path="basic-statistics.html"><a href="basic-statistics.html#one-way-repeated-measures-anova"><i class="fa fa-check"></i><b>10.6.6</b> One-way Repeated Measures ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="basic-statistics.html"><a href="basic-statistics.html#two-way-anova"><i class="fa fa-check"></i><b>10.7</b> Two-way ANOVA</a>
<ul>
<li class="chapter" data-level="10.7.1" data-path="basic-statistics.html"><a href="basic-statistics.html#identifying-outliers"><i class="fa fa-check"></i><b>10.7.1</b> Identifying Outliers</a></li>
<li class="chapter" data-level="10.7.2" data-path="basic-statistics.html"><a href="basic-statistics.html#checking-for-normality-of-data-1"><i class="fa fa-check"></i><b>10.7.2</b> Checking for Normality of Data</a></li>
<li class="chapter" data-level="10.7.3" data-path="basic-statistics.html"><a href="basic-statistics.html#computing-two-way-anova"><i class="fa fa-check"></i><b>10.7.3</b> Computing Two-way ANOVA</a></li>
<li class="chapter" data-level="10.7.4" data-path="basic-statistics.html"><a href="basic-statistics.html#post-hoc-test"><i class="fa fa-check"></i><b>10.7.4</b> Post-hoc Test</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="basic-statistics.html"><a href="basic-statistics.html#extra-resources"><i class="fa fa-check"></i><b>10.8</b> Extra Resources</a></li>
</ul></li>
<li class="part"><span><b>III Manual for smplot2</b></span></li>
<li class="chapter" data-level="11" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><i class="fa fa-check"></i><b>11</b> Themes, Colors, Correlations, Boxplots, Violins and Bars (Part 1)</a>
<ul>
<li class="chapter" data-level="11.1" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#installation-of-the-package"><i class="fa fa-check"></i><b>11.1</b> Installation of the Package</a></li>
<li class="chapter" data-level="11.2" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#how-...-parameter-and-xxx.params-work"><i class="fa fa-check"></i><b>11.2</b> How <code>...</code> parameter and <code>xxx.params</code> work</a></li>
<li class="chapter" data-level="11.3" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#color-palette"><i class="fa fa-check"></i><b>11.3</b> Color palette</a></li>
<li class="chapter" data-level="11.4" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#graph-themes"><i class="fa fa-check"></i><b>11.4</b> Graph themes</a></li>
<li class="chapter" data-level="11.5" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#correlation-plot"><i class="fa fa-check"></i><b>11.5</b> Correlation plot</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#sm_statcorr"><i class="fa fa-check"></i><b>11.5.1</b> <code>sm_statCorr()</code></a></li>
<li class="chapter" data-level="11.5.2" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#sm_corr_avgerr"><i class="fa fa-check"></i><b>11.5.2</b> <code>sm_corr_avgErr()</code></a></li>
<li class="chapter" data-level="11.5.3" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#structure-of-data-frame"><i class="fa fa-check"></i><b>11.5.3</b> Structure of data frame</a></li>
<li class="chapter" data-level="11.5.4" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#correlation-plot-with-both-regression-and-reference-lines"><i class="fa fa-check"></i><b>11.5.4</b> Correlation plot with both regression and reference lines</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#boxplot---sm_boxplot"><i class="fa fa-check"></i><b>11.6</b> Boxplot - <code>sm_boxplot()</code></a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#plotting-individual-points-with-unique-colors-1"><i class="fa fa-check"></i><b>11.6.1</b> Plotting individual points with unique colors</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#violin-plot---sm_violin"><i class="fa fa-check"></i><b>11.7</b> Violin Plot - <code>sm_violin()</code></a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#plotting-individual-points-with-unique-colors-2"><i class="fa fa-check"></i><b>11.7.1</b> Plotting individual points with unique colors</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#bar-plot---sm_bar"><i class="fa fa-check"></i><b>11.8</b> Bar plot - <code>sm_bar()</code></a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="themes-colors-correlations-boxplots-violins-and-bars-part-1.html"><a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html#plotting-individual-points-with-unique-colors-3"><i class="fa fa-check"></i><b>11.8.1</b> Plotting individual points with unique colors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><a href="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><i class="fa fa-check"></i><b>12</b> Slope Charts, Point plots, Bland-Altman, Forests, Rainclouds, Histograms (Part 2)</a>
<ul>
<li class="chapter" data-level="12.1" data-path="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><a href="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html#slope-chart---sm_slope"><i class="fa fa-check"></i><b>12.1</b> Slope chart - <code>sm_slope()</code></a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><a href="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html#drawing-the-mean-plot"><i class="fa fa-check"></i><b>12.1.1</b> Drawing the mean plot</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><a href="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html#point-plot---sm_pointplot"><i class="fa fa-check"></i><b>12.2</b> Point plot - <code>sm_pointplot()</code></a></li>
<li class="chapter" data-level="12.3" data-path="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><a href="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html#a-bland-altman-plot---sm_bland_altman"><i class="fa fa-check"></i><b>12.3</b> A Bland Altman plot - <code>sm_bland_altman()</code></a></li>
<li class="chapter" data-level="12.4" data-path="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><a href="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html#forest-plot---sm_forest"><i class="fa fa-check"></i><b>12.4</b> Forest plot - <code>sm_forest()</code></a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><a href="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html#annotation-using-sm_forest_annot"><i class="fa fa-check"></i><b>12.4.1</b> Annotation using <code>sm_forest_annot()</code></a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><a href="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html#raincloud-plot---sm_raincloud"><i class="fa fa-check"></i><b>12.5</b> Raincloud plot - <code>sm_raincloud()</code></a></li>
<li class="chapter" data-level="12.6" data-path="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html"><a href="slope-charts-point-plots-bland-altman-forests-rainclouds-histograms-part-2.html#histogram---sm_hist"><i class="fa fa-check"></i><b>12.6</b> Histogram - <code>sm_hist()</code></a></li>
</ul></li>
<li class="part"><span><b>IV Contrast Sensitivity Function</b></span></li>
<li class="chapter" data-level="13" data-path="plotting-the-contrast-sensitivity-function.html"><a href="plotting-the-contrast-sensitivity-function.html"><i class="fa fa-check"></i><b>13</b> Plotting the Contrast Sensitivity Function</a>
<ul>
<li class="chapter" data-level="13.1" data-path="plotting-the-contrast-sensitivity-function.html"><a href="plotting-the-contrast-sensitivity-function.html#brief-introduction"><i class="fa fa-check"></i><b>13.1</b> Brief Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="plotting-the-contrast-sensitivity-function.html"><a href="plotting-the-contrast-sensitivity-function.html#data-visualization"><i class="fa fa-check"></i><b>13.2</b> Data Visualization</a></li>
<li class="chapter" data-level="13.3" data-path="plotting-the-contrast-sensitivity-function.html"><a href="plotting-the-contrast-sensitivity-function.html#facetting-the-contrast-sensitivity-functions"><i class="fa fa-check"></i><b>13.3</b> Facetting the Contrast Sensitivity Functions</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="area-under-curve-aulcsf-and-r2-of-the-csf.html"><a href="area-under-curve-aulcsf-and-r2-of-the-csf.html"><i class="fa fa-check"></i><b>14</b> Area under Curve, AULCSF and R2 of the CSF</a>
<ul>
<li class="chapter" data-level="14.1" data-path="area-under-curve-aulcsf-and-r2-of-the-csf.html"><a href="area-under-curve-aulcsf-and-r2-of-the-csf.html#area-under-a-curve-1"><i class="fa fa-check"></i><b>14.1</b> Area under a Curve</a></li>
<li class="chapter" data-level="14.2" data-path="area-under-curve-aulcsf-and-r2-of-the-csf.html"><a href="area-under-curve-aulcsf-and-r2-of-the-csf.html#sm_trapz-sm_aulcsf-and-sm_r2"><i class="fa fa-check"></i><b>14.2</b> <code>sm_trapz()</code>, <code>sm_AULCSF()</code> and <code>sm_r2()</code></a></li>
<li class="chapter" data-level="14.3" data-path="area-under-curve-aulcsf-and-r2-of-the-csf.html"><a href="area-under-curve-aulcsf-and-r2-of-the-csf.html#calculating-area-and-r2-of-all-subjects-groups-and-conditions"><i class="fa fa-check"></i><b>14.3</b> Calculating area and R2 of all subjects, groups and conditions</a></li>
<li class="chapter" data-level="14.4" data-path="area-under-curve-aulcsf-and-r2-of-the-csf.html"><a href="area-under-curve-aulcsf-and-r2-of-the-csf.html#case-study"><i class="fa fa-check"></i><b>14.4</b> Case Study</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="understanding-the-contrast-sensitivity-function.html"><a href="understanding-the-contrast-sensitivity-function.html"><i class="fa fa-check"></i><b>15</b> Understanding the Contrast Sensitivity Function</a>
<ul>
<li class="chapter" data-level="15.1" data-path="understanding-the-contrast-sensitivity-function.html"><a href="understanding-the-contrast-sensitivity-function.html#contrast-sensitivity-function-model"><i class="fa fa-check"></i><b>15.1</b> Contrast Sensitivity Function Model</a></li>
<li class="chapter" data-level="15.2" data-path="understanding-the-contrast-sensitivity-function.html"><a href="understanding-the-contrast-sensitivity-function.html#understanding-sm_csf"><i class="fa fa-check"></i><b>15.2</b> Understanding <code>sm_CSF()</code></a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="understanding-the-contrast-sensitivity-function.html"><a href="understanding-the-contrast-sensitivity-function.html#sm_params"><i class="fa fa-check"></i><b>15.2.1</b> <code>sm_params()</code></a></li>
<li class="chapter" data-level="15.2.2" data-path="understanding-the-contrast-sensitivity-function.html"><a href="understanding-the-contrast-sensitivity-function.html#sm_cutoff"><i class="fa fa-check"></i><b>15.2.2</b> <code>sm_cutOff()</code></a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="understanding-the-contrast-sensitivity-function.html"><a href="understanding-the-contrast-sensitivity-function.html#understanding-sm_ribboncsf"><i class="fa fa-check"></i><b>15.3</b> Understanding <code>sm_ribbonCSF()</code></a></li>
<li class="chapter" data-level="15.4" data-path="understanding-the-contrast-sensitivity-function.html"><a href="understanding-the-contrast-sensitivity-function.html#calculating-the-five-parameters-of-all-subjects-groups-and-conditions"><i class="fa fa-check"></i><b>15.4</b> Calculating the five parameters of all subjects, groups and conditions</a></li>
<li class="chapter" data-level="15.5" data-path="understanding-the-contrast-sensitivity-function.html"><a href="understanding-the-contrast-sensitivity-function.html#visualization-of-the-parameters"><i class="fa fa-check"></i><b>15.5</b> Visualization of the parameters</a></li>
<li class="chapter" data-level="15.6" data-path="understanding-the-contrast-sensitivity-function.html"><a href="understanding-the-contrast-sensitivity-function.html#case-study-1"><i class="fa fa-check"></i><b>15.6</b> Case Study</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Analysis and Visualization in R Using smplot2</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="basic-statistics" class="section level1" number="10">
<h1><span class="header-section-number">Chapter 10</span> Basic Statistics</h1>
<p>As in the previous two chapters, we will continue to use data from this paper (<a href="https://www.smin95.com/pubs/min2019.pdf">PDF</a>):</p>
<p><strong>Seung Hyun Min, Alex S. Baldwin and Robert F. Hess. Ocular dominance plasticity: A binocular combination task finds no cumulative effect with repeated patching (2019). Vision Research, 161, 36-42.</strong></p>
<p>Load the <code>tidyverse</code> and other libraries, and the csv file <code>min2019b.csv</code> using <code>read_csv()</code> from the <code>tidyverse</code> package.</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="basic-statistics.html#cb440-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb440-2"><a href="basic-statistics.html#cb440-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(smplot2)</span>
<span id="cb440-3"><a href="basic-statistics.html#cb440-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cowplot)</span>
<span id="cb440-4"><a href="basic-statistics.html#cb440-4" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://www.smin95.com/min2019b.csv&#39;</span>) </span>
<span id="cb440-5"><a href="basic-statistics.html#cb440-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 4
##   Subject   Day  Time Cbratio
##   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1 a           1     0  -0.421
## 2 b           1     0   2.82 
## 3 c           1     0   1.69 
## 4 d           1     0   2.55 
## 5 e           1     0  -0.217
## 6 f           1     0   0.626</code></pre>
<div id="one-sample-t-test" class="section level2" number="10.1">
<h2><span class="header-section-number">10.1</span> One-sample t-test</h2>
<p>One sample t-test compares the mean of a sample to a hypothesized mean (often 0).</p>
<p>For example, here is Figure 3E from the paper. What do the *** mean? How about ** and *? Let’s take a look.</p>
<pre><code>## Rows: 51 Columns: 3
## -- Column specification --------------------------------------------------------
## Delimiter: &quot;,&quot;
## dbl (3): x, y_mean, y_se
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
## Rows: 300 Columns: 4
## -- Column specification --------------------------------------------------------
## Delimiter: &quot;,&quot;
## chr (1): Subject
## dbl (3): Day, Time, Cbratio
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
## sm_auc_list is deprecated. Use sm_auc_all instead.</code></pre>
<pre><code>## [1] &quot;AUC = Cbratio * Time&quot;</code></pre>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-327-1.png" width="336" /></p>
<p>For instance, to determine if the area under curve (changes in contrast balance ratio over time) after patching is significant, so much so that one can confidently say that it is different from 0, we can perform a one-sample t-test using <code>t.test()</code>.</p>
<p>Let’s use data from the sampe paper. We import the data from online using <code>read_csv()</code> and store them into a variable (in this case, <code>df</code>). Then, we compute the area under a curve using <code>sm_auc_list()</code> and store the values in the variable <code>auc_df</code>.</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="basic-statistics.html#cb444-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://www.smin95.com/min2019b.csv&#39;</span>) </span>
<span id="cb444-2"><a href="basic-statistics.html#cb444-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb444-3"><a href="basic-statistics.html#cb444-3" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Day <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>Day)</span>
<span id="cb444-4"><a href="basic-statistics.html#cb444-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb444-5"><a href="basic-statistics.html#cb444-5" aria-hidden="true" tabindex="-1"></a>auc_df <span class="ot">&lt;-</span> <span class="fu">sm_auc_list</span>(<span class="at">subjects =</span> <span class="st">&#39;Subject&#39;</span>, <span class="at">conditions =</span> <span class="st">&#39;Day&#39;</span>, </span>
<span id="cb444-6"><a href="basic-statistics.html#cb444-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">x =</span> <span class="st">&#39;Time&#39;</span>, <span class="at">values =</span> <span class="st">&#39;Cbratio&#39;</span>,</span>
<span id="cb444-7"><a href="basic-statistics.html#cb444-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## [1] &quot;AUC = Cbratio * Time&quot;</code></pre>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="basic-statistics.html#cb446-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(auc_df)</span></code></pre></div>
<pre><code>##   Subject Day AUC_Cbratio
## 1       a   1    -2.36910
## 2       a   2     0.68265
## 3       a   3    -9.54795
## 4       a   4    27.12165
## 5       a   5    41.95680
## 6       b   1    60.52860</code></pre>
<p>The <code>Day</code> column of <code>df</code> has to be factored using <code>as.factor()</code> because <code>Day</code> here is a categorical, rather than, continuous variable.</p>
<p>To determine if the area under curve data on Day 1 were significantly different from 0, we could use one-sample t-test. First, let’s filter for data from only Day 1.</p>
<div class="sourceCode" id="cb448"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb448-1"><a href="basic-statistics.html#cb448-1" aria-hidden="true" tabindex="-1"></a>auc_df_day1 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb448-2"><a href="basic-statistics.html#cb448-2" aria-hidden="true" tabindex="-1"></a>auc_df_day1</span></code></pre></div>
<pre><code>##    Subject Day AUC_Cbratio
## 1        a   1    -2.36910
## 2        b   1    60.52860
## 3        c   1    94.84035
## 4        d   1   100.62510
## 5        e   1    55.32240
## 6        f   1   108.13770
## 7        g   1    63.27840
## 8        h   1    48.71625
## 9        u   1    39.11865
## 10       j   1    74.90610</code></pre>
<p>Then, lets extract the values from the <code>AUC_Cbratio</code> column and perform one-sample t-test using <code>t.test()</code>.</p>
<div class="sourceCode" id="cb450"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb450-1"><a href="basic-statistics.html#cb450-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  auc_df_day1$AUC_Cbratio
## t = 6.1934, df = 9, p-value = 0.0001601
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  40.82072 87.80017
## sample estimates:
## mean of x 
##  64.31045</code></pre>
<p><code>mu = 0</code> is included as an argument when performing one-sample <code>t.test</code>; this means an average of 0. In this case, you are comparing the data from <code>auc_df_day1$AUC_Cbratio</code> to <code>mu = 0</code>.</p>
<p>The p-value must be less than <strong>0.05</strong> to be considered statistically significant. It is labelled with one asterisk *. 0.001 &lt; p &lt; 0.01 is denoted with two asterisks **, and p &lt; 0.001 is denoted with three asterisks ***. Since the p-value reported here is less than 0.001, Figure 3E has *** for Day 1’s area under a curve.</p>
<p>We can repeat this for Days 2-5. For brevity, we repeat the example with Days 2 and 4 only.</p>
<div class="sourceCode" id="cb452"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb452-1"><a href="basic-statistics.html#cb452-1" aria-hidden="true" tabindex="-1"></a>auc_df_day2 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">2</span>)</span>
<span id="cb452-2"><a href="basic-statistics.html#cb452-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day2<span class="sc">$</span>AUC_Cbratio, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  auc_df_day2$AUC_Cbratio
## t = 3.5182, df = 9, p-value = 0.006534
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  19.60882 90.24161
## sample estimates:
## mean of x 
##  54.92521</code></pre>
<p>The p value is 0.0065, which is less than 0.01 but larger than 0.001. In this case, the statistical significane is denoted as **. Likewise, Figure 3E shows the AUC of Day 2 with **.</p>
<div class="sourceCode" id="cb454"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb454-1"><a href="basic-statistics.html#cb454-1" aria-hidden="true" tabindex="-1"></a>auc_df_day4 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">4</span>)</span>
<span id="cb454-2"><a href="basic-statistics.html#cb454-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day4<span class="sc">$</span>AUC_Cbratio, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  auc_df_day4$AUC_Cbratio
## t = 3.0973, df = 9, p-value = 0.01278
## alternative hypothesis: true mean is not equal to 0
## 95 percent confidence interval:
##  11.71639 75.19169
## sample estimates:
## mean of x 
##  43.45404</code></pre>
<p>The p-value is 0.013, which is less than 0.05 but larger than 0.01. Therefore one asterisk * is used to label the statistical significance.</p>
</div>
<div id="two-sample-t-test" class="section level2" number="10.2">
<h2><span class="header-section-number">10.2</span> Two-sample t-test</h2>
<p>A two-sample t-test is used to compare the mean of one sample to that of another sample.</p>
<p>For example, let’s compare changes in sensory eye dominance after short-term monocular deprivation in Day 1 vs Day 5. These values are shown in the <code>Cbratio</code> column.</p>
<p>Let’s filter only for AUC data from Days 1 and 5.</p>
<div class="sourceCode" id="cb456"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb456-1"><a href="basic-statistics.html#cb456-1" aria-hidden="true" tabindex="-1"></a>auc_df_day1 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb456-2"><a href="basic-statistics.html#cb456-2" aria-hidden="true" tabindex="-1"></a>auc_df_day5 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">5</span>)</span>
<span id="cb456-3"><a href="basic-statistics.html#cb456-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb456-4"><a href="basic-statistics.html#cb456-4" aria-hidden="true" tabindex="-1"></a>auc_df_day15 <span class="ot">&lt;-</span> auc_df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Day <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> Day <span class="sc">==</span> <span class="dv">5</span>)</span></code></pre></div>
<p>Now, let’s plot a bar graph to display the AUC from Days 1 and 5 using <code>sm_bar()</code>.</p>
<div class="sourceCode" id="cb457"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb457-1"><a href="basic-statistics.html#cb457-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> auc_df_day15, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Day, <span class="at">y =</span> AUC_Cbratio, <span class="at">color =</span> Day)) <span class="sc">+</span></span>
<span id="cb457-2"><a href="basic-statistics.html#cb457-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sm_bar</span>(<span class="at">shape =</span> <span class="dv">21</span>) <span class="sc">+</span></span>
<span id="cb457-3"><a href="basic-statistics.html#cb457-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">sm_color</span>(<span class="st">&#39;blue&#39;</span>,<span class="st">&#39;orange&#39;</span>)) <span class="sc">+</span></span>
<span id="cb457-4"><a href="basic-statistics.html#cb457-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&#39;AUC in Days 1 and 5&#39;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-334-1.png" width="355.2" /></p>
<p>There seems to be a difference in the AUC <code>AUC_Cbratio</code> between Days 1 and 5. The error bars (in this case, standard error) are barely overlapping. If the error bars are clearly overlapping, there is often no significant difference (p &lt; 0.05) between the two data sets. If there is no overlap, it is highly likely that a statistical test will show a significant difference (p &lt; 0.05). Let’s take a look using <strong>t-test</strong> using the function <code>t.test()</code>.</p>
<p><code>t.test()</code> allows us to compare whether data between two different groups are significantly different. Here, <code>$</code> is used to <strong>extract</strong> data from a specific column within a data frame. You could type <code>df_0min$</code>, press the <strong>Tab</strong> button from the keyboard, and see what happens. Since we will only compare values in the <code>AUC_Cbratio</code> column, let’s select for the <code>AUC_Cbratio</code> column and use these values in our <code>t.test()</code>.</p>
<div class="sourceCode" id="cb458"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb458-1"><a href="basic-statistics.html#cb458-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, auc_df_day5<span class="sc">$</span>AUC_Cbratio, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  auc_df_day1$AUC_Cbratio and auc_df_day5$AUC_Cbratio
## t = 1.5694, df = 9, p-value = 0.151
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -10.17563  56.27723
## sample estimates:
## mean of the differences 
##                 23.0508</code></pre>
<p>In this case, the subjects are <strong>paired</strong> because the 10 subjects performed on both Days 1 and 5. If your data are not paired (ex. patients vs controls) and you want to perform a t-test, you can set <code>paired = FALSE</code>.</p>
<p>If we are reporting the results, we should report it as such, t(9) = 1.57, p = 0.15. The difference between Days 1 and 5 is not statistically significant.</p>
<div id="shapiro-wilk-test-to-test-for-normality-of-data" class="section level3" number="10.2.1">
<h3><span class="header-section-number">10.2.1</span> Shapiro-Wilk Test to test for Normality of Data</h3>
<p>T-test can only be used when the data assume normality. In other word, the data that are to be analyzed using <code>t.test()</code> must have a normal distribution (shown below).</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-336-1.png" width="355.2" /></p>
<p>Whether the data have a normal distribution can be checked using a Shaprio-Wilk test (<code>shapiro.test()</code>). If p &gt; 0.05, then the data have a normal distribution, and therefore, t-test can be used to analyze the data. If p &lt; 0.05, the data are not normally distributed, and t-test cannot be used.</p>
<p>For example, let’s check whether the AUC data from Day 1 have a normal distribution.</p>
<div class="sourceCode" id="cb460"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb460-1"><a href="basic-statistics.html#cb460-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  auc_df_day1$AUC_Cbratio
## W = 0.95039, p-value = 0.6732</code></pre>
<p>P value is 0.67, which is larger than 0.05. Therefore, the AUCs from Day 1 have a normal distribution.</p>
<div class="sourceCode" id="cb462"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb462-1"><a href="basic-statistics.html#cb462-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(auc_df_day5<span class="sc">$</span>AUC_Cbratio)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  auc_df_day5$AUC_Cbratio
## W = 0.97531, p-value = 0.9353</code></pre>
<p>P value is 0.935, which is larger than 0.05. Therefore, the AUCs from Day 5 have a normal distribution. More information about <code>shapiro.test()</code> can be found in this link: <a href="http://www.sthda.com/english/wiki/normality-test-in-r" class="uri">http://www.sthda.com/english/wiki/normality-test-in-r</a>.</p>
<p>T-test is a type of <strong>parametric</strong> statistical test, which is used to analyze data that are normally distributed. If the data are not normally distributed, <strong>non-parametric</strong> statistical test can be used.</p>
</div>
</div>
<div id="wilcoxon-signed-rank-test" class="section level2" number="10.3">
<h2><span class="header-section-number">10.3</span> Wilcoxon Signed-rank Test</h2>
<p>Wilcoxon Signed-rank Test is a <strong>non-parametric</strong> statistical test that is used instead of a t-test when the data are <strong>not normally distributed</strong>.</p>
<p>If Shaprio-Wilk test yields p &lt; 0.05 for the following datasets, a Wilcoxon Signed Rank Test must be used for both one-sample and two-sample tests.</p>
<div class="sourceCode" id="cb464"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb464-1"><a href="basic-statistics.html#cb464-1" aria-hidden="true" tabindex="-1"></a><span class="co"># one-sample Wilcoxon Signed-rank Test</span></span>
<span id="cb464-2"><a href="basic-statistics.html#cb464-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, <span class="at">mu =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  auc_df_day1$AUC_Cbratio
## V = 54, p-value = 0.003906
## alternative hypothesis: true location is not equal to 0</code></pre>
<p>The p-value is 0.0039, which is less than 0.05. Therefore, according to the Wilcoxon test, the AUCs from Day 1 are significantly different from 0.</p>
<div class="sourceCode" id="cb466"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb466-1"><a href="basic-statistics.html#cb466-1" aria-hidden="true" tabindex="-1"></a><span class="co"># two-sample Wilcoxon test</span></span>
<span id="cb466-2"><a href="basic-statistics.html#cb466-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, auc_df_day5<span class="sc">$</span>AUC_Cbratio, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Wilcoxon signed rank exact test
## 
## data:  auc_df_day1$AUC_Cbratio and auc_df_day5$AUC_Cbratio
## V = 43, p-value = 0.1309
## alternative hypothesis: true location shift is not equal to 0</code></pre>
<p>The p-value is 0.13, which is larger than 0.05. Therefore, according to the Wilcoxon test, the AUCs from Days 1 and 5 are not significantly different.</p>
</div>
<div id="effect-size" class="section level2" number="10.4">
<h2><span class="header-section-number">10.4</span> Effect Size</h2>
<p>However, even if p-value is larger than 0.05, this does not mean that there is no significant difference between the two groups/conditions. In fact, even a strong drug effect in a study that compares placebo vs. drug can result in p &gt; 0.05 if the sample size is too small.</p>
<p>On the other hand, if a study is conducted with a very large sample size (1000 patients per group) to examine the effect of a very weak drug, the data between weak drug and control can give us a p &lt; 0.05, which indicates a statistically significant difference.</p>
<p>In short, <strong>p-value is not everything because it depends on the sample size.</strong></p>
<p>If the sample size is small, p-value can be larger than 0.05. But as the sample gets larger, p-value will decrease even if the mean difference between the two groups remains the same.</p>
<p>In this example, the sample size is not large (n=10). Therefore, one might ask whether our conclusion that there is no significant difference between Days 1 and 5 is truly valid. One might also believe that if our sample size was larger (ex. n=50), we would have found a significant difference between Days 1 and 5.</p>
<p>To respond to this concern, we might need to calculate the <strong>effect size</strong>. If the effect size is large, there is a large difference between the sample groups. <strong>Unlike the p-value, the effect size does not depend on the sample size.</strong></p>
<p>One measure to capture the effect size is <strong>Cohen’s d</strong>. We can use <code>sm_effsize()</code> to calculate Cohen’s d as a measure for the effect size.</p>
<ul>
<li><strong>Small</strong> effect size: Cohen’s d around <strong>0.2</strong></li>
<li><strong>Medium</strong> effect size: Cohen’s d around <strong>0.5</strong></li>
<li><strong>Large</strong> effect size: Cohen’s d &gt; <strong>0.8</strong>.</li>
</ul>
<p>The inputs for <code>sm_effsize()</code> are the data of two sample groups, just as they were in <code>t.test()</code>.</p>
<p>Let’s compute the effect size (Cohen’s d) using AUC data from Days 1 and 2.</p>
<div class="sourceCode" id="cb468"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb468-1"><a href="basic-statistics.html#cb468-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sm_effsize</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, auc_df_day2<span class="sc">$</span>AUC_Cbratio)</span></code></pre></div>
<pre><code>## [1] 0.2238542</code></pre>
<p>Cohen’s d equals <strong>0.224</strong>, which is a very small effect size. This indicates that there is a very small difference in AUC between Days 1 and 2.</p>
<div class="sourceCode" id="cb470"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb470-1"><a href="basic-statistics.html#cb470-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day1<span class="sc">$</span>AUC_Cbratio, auc_df_day2<span class="sc">$</span>AUC_Cbratio,</span>
<span id="cb470-2"><a href="basic-statistics.html#cb470-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  auc_df_day1$AUC_Cbratio and auc_df_day2$AUC_Cbratio
## t = 0.46312, df = 9, p-value = 0.6543
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -36.45777  55.22823
## sample estimates:
## mean of the differences 
##                 9.38523</code></pre>
<p>Also, it is recommended that <strong>both p-value and effect size are reported</strong> at all times. In this example, I would report the results as: <strong>t(9) = 0.46, p = 0.65, Cohen’s d = 0.22</strong>.</p>
<p>Let’s see what happens in the effect size and p-value from t-test if there are 1000 subjects.</p>
<div class="sourceCode" id="cb472"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb472-1"><a href="basic-statistics.html#cb472-1" aria-hidden="true" tabindex="-1"></a>auc_df_day1b <span class="ot">&lt;-</span> <span class="fu">do.call</span>(<span class="st">&#39;rbind&#39;</span>, <span class="fu">replicate</span>(<span class="dv">100</span>, auc_df_day1, <span class="at">simplify =</span> <span class="cn">FALSE</span>))</span>
<span id="cb472-2"><a href="basic-statistics.html#cb472-2" aria-hidden="true" tabindex="-1"></a>auc_df_day1b<span class="sc">$</span>Subject <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&#39;S&#39;</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>)</span>
<span id="cb472-3"><a href="basic-statistics.html#cb472-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(auc_df_day1b, <span class="dv">30</span>)</span></code></pre></div>
<pre><code>##    Subject Day AUC_Cbratio
## 1       S1   1    -2.36910
## 2       S2   1    60.52860
## 3       S3   1    94.84035
## 4       S4   1   100.62510
## 5       S5   1    55.32240
## 6       S6   1   108.13770
## 7       S7   1    63.27840
## 8       S8   1    48.71625
## 9       S9   1    39.11865
## 10     S10   1    74.90610
## 11     S11   1    -2.36910
## 12     S12   1    60.52860
## 13     S13   1    94.84035
## 14     S14   1   100.62510
## 15     S15   1    55.32240
## 16     S16   1   108.13770
## 17     S17   1    63.27840
## 18     S18   1    48.71625
## 19     S19   1    39.11865
## 20     S20   1    74.90610
## 21     S21   1    -2.36910
## 22     S22   1    60.52860
## 23     S23   1    94.84035
## 24     S24   1   100.62510
## 25     S25   1    55.32240
## 26     S26   1   108.13770
## 27     S27   1    63.27840
## 28     S28   1    48.71625
## 29     S29   1    39.11865
## 30     S30   1    74.90610</code></pre>
<p>We have replicated all the rows of the data frame <code>auc_df_day1</code> by 100 times to create 1000 rows total (i.e., 1000 subjects).</p>
<div class="sourceCode" id="cb474"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb474-1"><a href="basic-statistics.html#cb474-1" aria-hidden="true" tabindex="-1"></a>auc_df_day2b <span class="ot">&lt;-</span> <span class="fu">do.call</span>(<span class="st">&#39;rbind&#39;</span>, <span class="fu">replicate</span>(<span class="dv">100</span>, auc_df_day2, <span class="at">simplify =</span> <span class="cn">FALSE</span>))</span>
<span id="cb474-2"><a href="basic-statistics.html#cb474-2" aria-hidden="true" tabindex="-1"></a>auc_df_day2b<span class="sc">$</span>Subject <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&#39;S&#39;</span>,<span class="dv">1</span><span class="sc">:</span><span class="dv">1000</span>)</span>
<span id="cb474-3"><a href="basic-statistics.html#cb474-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(auc_df_day2b, <span class="dv">30</span>)</span></code></pre></div>
<pre><code>##    Subject Day AUC_Cbratio
## 1       S1   2     0.68265
## 2       S2   2    80.38215
## 3       S3   2     1.78695
## 4       S4   2   -19.60125
## 5       S5   2   132.99825
## 6       S6   2    31.14285
## 7       S7   2    80.24685
## 8       S8   2    75.98130
## 9       S9   2    64.56690
## 10     S10   2   101.06550
## 11     S11   2     0.68265
## 12     S12   2    80.38215
## 13     S13   2     1.78695
## 14     S14   2   -19.60125
## 15     S15   2   132.99825
## 16     S16   2    31.14285
## 17     S17   2    80.24685
## 18     S18   2    75.98130
## 19     S19   2    64.56690
## 20     S20   2   101.06550
## 21     S21   2     0.68265
## 22     S22   2    80.38215
## 23     S23   2     1.78695
## 24     S24   2   -19.60125
## 25     S25   2   132.99825
## 26     S26   2    31.14285
## 27     S27   2    80.24685
## 28     S28   2    75.98130
## 29     S29   2    64.56690
## 30     S30   2   101.06550</code></pre>
<p>We have replicated all the rows of the data frame <code>auc_df_day2</code> by 100 times to create 1000 rows total (i.e., 1000 subjects).</p>
<div class="sourceCode" id="cb476"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb476-1"><a href="basic-statistics.html#cb476-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sm_effsize</span>(auc_df_day1b<span class="sc">$</span>AUC_Cbratio, auc_df_day2b<span class="sc">$</span>AUC_Cbratio)</span></code></pre></div>
<pre><code>## [1] 0.2358451</code></pre>
<p>The effect size is 0.24. It has barely changed despite the significantly larger sample size.</p>
<div class="sourceCode" id="cb478"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb478-1"><a href="basic-statistics.html#cb478-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(auc_df_day1b<span class="sc">$</span>AUC_Cbratio, auc_df_day2b<span class="sc">$</span>AUC_Cbratio,</span>
<span id="cb478-2"><a href="basic-statistics.html#cb478-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> T)</span></code></pre></div>
<pre><code>## 
##  Paired t-test
## 
## data:  auc_df_day1b$AUC_Cbratio and auc_df_day2b$AUC_Cbratio
## t = 4.8793, df = 999, p-value = 1.239e-06
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   5.610696 13.159764
## sample estimates:
## mean of the differences 
##                 9.38523</code></pre>
<p>Now, the p-value is <strong>much less than 0.001</strong>, rather than staying at 0.65. Therefore, we can now observe that p-value is heavily affected by the sample size, whereas the effect size (Cohen’s d) does not. In short, as the sample size increases, the p-value decreases even if the effect size stays the same.</p>
</div>
<div id="power-analysis" class="section level2" number="10.5">
<h2><span class="header-section-number">10.5</span> Power Analysis</h2>
<p>We got p &gt; 0.05 with our small sample size (n = 10). As we previously mentioned, we know that p-value gets smaller with an increasing sample size. <strong>Therefore, given the mean difference between two sample groups (i.e., same effect size), the p-value can change depending on the sample size</strong>. So, it is important to report both the p-value and the effect size.</p>
<p>So, one might be concerned with what would be the minimal sample size to detect a statistically significant difference between the two groups (Days 1 and 5). This can be achieved using <strong>power analysis</strong>. Note that p can always be less than 0.05 as long as the sample size meets the requirement (i.e., very large).</p>
<p>If the effect size was large but the data yielded p &gt; 0.05, then we could predict that the minimal sample size from power analysis would be not large. If the effect size was small and the data yielded p &gt; 0.05, as it was for my data, the minimal sample size to yield p &lt; 0.05 would need to be very large.</p>
<p>If the minimal sample size from power analysis was not large (hence, large effect size), then one could conclude that I did not collect enough data and incorrectly concluded that there was no significant difference between the two groups. This would be so because if the sample size was larger, I would have gotten p &lt; 0.05.</p>
<p><strong>Power analysis</strong> can be performed using <code>sm_power()</code>. The inputs for <code>sm_power()</code> are data of two sample groups, just as they were in <code>t.test()</code>.</p>
<div class="sourceCode" id="cb480"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb480-1"><a href="basic-statistics.html#cb480-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sm_power</span>(auc_df_day1b<span class="sc">$</span>AUC_Cbratio, auc_df_day2b<span class="sc">$</span>AUC_Cbratio,</span>
<span id="cb480-2"><a href="basic-statistics.html#cb480-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##      Paired t test power calculation 
## 
##               n = 143.0411
##               d = 0.2358451
##       sig.level = 0.05
##           power = 0.8
##     alternative = two.sided
## 
## NOTE: n is number of *pairs*</code></pre>
<p>According to our power analysis (significant level = 0.05, power = 80%), we would need about <strong>143 subjects</strong> per group (<code>n = 143.0411</code>) for the p-value to reach below 0.05 and, therefore, for us to detect a statistically significant difference in AUCs between Days 1 and 2. In other words, the difference between Days 1 and 2 is very small. Also, the conclusion that there was no difference between the days seems to be valid even though the sample size is small.</p>
</div>
<div id="one-way-anova" class="section level2" number="10.6">
<h2><span class="header-section-number">10.6</span> One-way ANOVA</h2>
<p>One-way analysis of variance (ANOVA) is used to compare the mean of multiple groups (2 groups or more). It can also be referred to as one-factor ANOVA. The data are separated into multiple groups based on one categorical variable (such as patching days, conditions or subject groups).</p>
<p>When one is comparing two groups, one-way ANOVA and two-sample t-test can yield the same results because both of these tests would compare two groups.</p>
<p>To do ANOVA, we will use <code>rstatix</code> package. Install the package if you have not done so.</p>
<div class="sourceCode" id="cb482"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb482-1"><a href="basic-statistics.html#cb482-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&#39;rstatix&#39;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb483"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb483-1"><a href="basic-statistics.html#cb483-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb483-2"><a href="basic-statistics.html#cb483-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span></code></pre></div>
<p><strong>Note:</strong> We will use <code>rstatix</code> to perform some statistical tests. However, both <code>tidyverse</code> and <code>rstatix</code> packages have the function called <code>filter()</code>. To use <code>filter()</code> from the <code>tidyverse</code> (or <code>dplyr</code>) package, as we have done so before, you will need to type <code>dplyr::filter</code> rather than <code>filter</code> instead to specify <code>filter()</code> from the <code>dplyr</code> package.</p>
<p>To perform ANOVA, we have to make some assumptions about the data:</p>
<ul>
<li><p>Data should be normally distributed. This can be confirmed by using a Shapiro-Wilk test.</p></li>
<li><p>No outliers.</p></li>
<li><p>Homogeneity of variance. The variance of the data should be consistent as a function of the predictor (x-axis). This can be examined with the Levene’s test.</p></li>
<li><p>Observations should be independent: The data from one group should have no relationship with other data within the same group. In short, each observation should be unique and come from an unique individual.</p></li>
</ul>
<p>Let’s investigate whether AUC data differ significantly across days (Days 1 to 5). To do so, we will need to perform one-way ANOVA where the factor is <code>Day</code>.</p>
<div id="check-for-outliers" class="section level3" number="10.6.1">
<h3><span class="header-section-number">10.6.1</span> Check for Outliers</h3>
<p>We will check for outliers in the <code>auc_df</code> data frame, which stores the results of AUCs. Since we will compare the AUCs across different days (factor: <code>Day</code>), we will group each observation (each row) of the data frame by <code>Day</code>. Next, we will use the function <code>identify_outliers()</code> from the <code>rstatix</code> package to see if there are any outliers in the data set.</p>
<div class="sourceCode" id="cb484"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb484-1"><a href="basic-statistics.html#cb484-1" aria-hidden="true" tabindex="-1"></a>auc_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Day) <span class="sc">%&gt;%</span></span>
<span id="cb484-2"><a href="basic-statistics.html#cb484-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">identify_outliers</span>(AUC_Cbratio)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   Day   Subject AUC_Cbratio is.outlier is.extreme
##   &lt;fct&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;lgl&gt;      &lt;lgl&gt;     
## 1 4     f              117. TRUE       TRUE      
## 2 4     g              132. TRUE       TRUE</code></pre>
<p>In this case, we have <strong>2 outliers</strong> of AUC data on Day 4. Since Figure 3E indicates that Day 4 is not outrageously different than the averaged AUCs of other days, I will infer that these 2 outliers do not significantly affect the data. Therefore, I will include these 2 outliers in my data analysis.</p>
<p>However, if your data set has too many outliers, then it might be inappropriate to proceed to one-way ANOVA.</p>
<p>Let’s visually confirm whether there are 2 outliers in the AUC data from Day 4 by plotting a boxplot using <code>sm_boxplot()</code>.</p>
<div class="sourceCode" id="cb486"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb486-1"><a href="basic-statistics.html#cb486-1" aria-hidden="true" tabindex="-1"></a>auc_df <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> Day, <span class="at">y =</span> AUC_Cbratio, <span class="at">color =</span> Day)) <span class="sc">+</span></span>
<span id="cb486-2"><a href="basic-statistics.html#cb486-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sm_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>,</span>
<span id="cb486-3"><a href="basic-statistics.html#cb486-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">point.params =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="fl">2.2</span>)) <span class="sc">+</span> </span>
<span id="cb486-4"><a href="basic-statistics.html#cb486-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">sm_palette</span>(<span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb486-5"><a href="basic-statistics.html#cb486-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&#39;\u0394 AUC re: Each day</span><span class="sc">\&#39;</span><span class="st">s baseline&#39;</span>)</span></code></pre></div>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-351-1.png" width="336" /></p>
<p>We see that there are two orange points that reside outside the whiskers of the boxplot. Points that are outside the whiskers represent outliers. Therefore, we confirm visually that there are two outliers on Day 4, and no outliers on any other days.</p>
</div>
<div id="checking-for-normality-of-data" class="section level3" number="10.6.2">
<h3><span class="header-section-number">10.6.2</span> Checking for Normality of Data</h3>
<p>Rather than using <code>shapiro.test()</code>, we will be using <code>shapiro_test()</code> from the <code>rstatix</code> package because we will be sorting data (<code>group_by()</code> by <code>Day</code>) using the pipe <code>%&gt;%</code>.</p>
<div class="sourceCode" id="cb487"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb487-1"><a href="basic-statistics.html#cb487-1" aria-hidden="true" tabindex="-1"></a>auc_df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Day) <span class="sc">%&gt;%</span></span>
<span id="cb487-2"><a href="basic-statistics.html#cb487-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro_test</span>(AUC_Cbratio)</span></code></pre></div>
<pre><code>## # A tibble: 5 x 4
##   Day   variable    statistic       p
##   &lt;fct&gt; &lt;chr&gt;           &lt;dbl&gt;   &lt;dbl&gt;
## 1 1     AUC_Cbratio     0.950 0.673  
## 2 2     AUC_Cbratio     0.944 0.599  
## 3 3     AUC_Cbratio     0.977 0.947  
## 4 4     AUC_Cbratio     0.770 0.00620
## 5 5     AUC_Cbratio     0.975 0.935</code></pre>
<p>In this data set, Days 1, 2, 3 and 5 have normally distributed data sets. However, the data from Day 4 do not seem to be normally distributed. This could because there are 2 outliers on Day 4. Since bulk of the data are normally distributed, I will use <strong>parametric</strong> method to analyze the data, i.e., one-way ANOVA. If most of your data are not normally distributed, then one-way ANOVA should not be used.</p>
</div>
<div id="checking-the-assumption-for-homogeneity-of-variance" class="section level3" number="10.6.3">
<h3><span class="header-section-number">10.6.3</span> Checking the Assumption for Homogeneity of Variance</h3>
<p>We can examine whether the variance of the response values (y values) is homogeneous using <code>levene_test()</code>.</p>
<div class="sourceCode" id="cb489"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb489-1"><a href="basic-statistics.html#cb489-1" aria-hidden="true" tabindex="-1"></a>auc_df <span class="sc">%&gt;%</span> <span class="fu">levene_test</span>(AUC_Cbratio <span class="sc">~</span> Day)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 4
##     df1   df2 statistic     p
##   &lt;int&gt; &lt;int&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1     4    45     0.638 0.638</code></pre>
<p>The Levene’s test shows that the p-value is 0.64, which is larger than 0.05. Therefore, we can assume that the variance is homogeneous across different days. Therefore, we can proceed to using ANOVA.</p>
</div>
<div id="computing-one-way-anova" class="section level3" number="10.6.4">
<h3><span class="header-section-number">10.6.4</span> Computing One-way ANOVA</h3>
<p>We perform one-way ANOVA by comparing whether <code>AUC_Cbratio</code> values significantly differ across <code>Day</code>. <code>~</code> (tilde) defines the relationship between dependent and independent variables. <code>y = m*x + b</code> can be described with <code>~</code> as <code>y~x</code>, where the value of x can affect the value of y. In the example below, it is written as <code>AUC_Cbratio ~ Day</code> because <code>AUC_Cbratio</code> (dependent variable) is affected by <code>Day</code> (independent variable).</p>
<div class="sourceCode" id="cb491"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb491-1"><a href="basic-statistics.html#cb491-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">formula =</span> AUC_Cbratio <span class="sc">~</span> Day, <span class="at">data =</span> auc_df)</span>
<span id="cb491-2"><a href="basic-statistics.html#cb491-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value Pr(&gt;F)
## Day          4   3513   878.3   0.588  0.673
## Residuals   45  67191  1493.1</code></pre>
<p><code>aov()</code> is used to perform <strong>a</strong>nalysis <strong>o</strong>f <strong>v</strong>ariance. In this example, the result from <code>aov()</code> is stored in the variable <code>res</code>. The summary of the results can be displayed using the function <code>summary()</code>.</p>
<p>The p-value is 0.67, which is larger than 0.05. This indicates that there is no significant difference across days in AUCs.</p>
<p>If your data show a p value less than 0.05, then you should proceed to the next step of performing post-hoc pairwise comparison tests.</p>
</div>
<div id="post-hoc-tests" class="section level3" number="10.6.5">
<h3><span class="header-section-number">10.6.5</span> Post-hoc Tests</h3>
<p>If one-way ANOVA shows a significant difference (p &lt; 0.05), then the reader should perform <strong>Tukey HSD</strong> post-hoc pairwise comparison (<strong>H</strong>onestly <strong>S</strong>ignificant <strong>D</strong>ifference) tests to see which two specific groups vary significantly. In the example, I have saved the results in the variable <code>res</code> (short for results).</p>
<div class="sourceCode" id="cb493"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb493-1"><a href="basic-statistics.html#cb493-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(res)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = AUC_Cbratio ~ Day, data = auc_df)
## 
## $Day
##           diff       lwr      upr     p adj
## 2-1  -9.385230 -58.48783 39.71737 0.9822382
## 3-1 -16.267650 -65.37025 32.83495 0.8791429
## 4-1 -20.856405 -69.95900 28.24619 0.7473960
## 5-1 -23.050800 -72.15340 26.05180 0.6718799
## 3-2  -6.882420 -55.98502 42.22018 0.9945038
## 4-2 -11.471175 -60.57377 37.63142 0.9630859
## 5-2 -13.665570 -62.76817 35.43703 0.9319698
## 4-3  -4.588755 -53.69135 44.51384 0.9988648
## 5-3  -6.783150 -55.88575 42.31945 0.9948024
## 5-4  -2.194395 -51.29699 46.90820 0.9999390</code></pre>
<p>As expected from one-way ANOVA, which shows no significant difference across days, the post-hoc pairwise tests (Tukey HSD test) yield p-values higher than 0.05 between any combinations of two different days.</p>
<p>If one-way ANOVA yielded p &lt; 0.05, then we could expect to see a p-value lower than 0.05 in the Tukey HSD post-hoc test. Therefore, when one-way ANOVA yields p &gt; 0.05, it is not necessary to perform a pairwise post-hoc comparison (Tukey HSD) using the data set.</p>
</div>
<div id="one-way-repeated-measures-anova" class="section level3" number="10.6.6">
<h3><span class="header-section-number">10.6.6</span> One-way Repeated Measures ANOVA</h3>
<p>If the subjects are identical across the factor (ex. <code>Day</code>), then <code>anova_test()</code> (from the <code>rstatix</code> package) can be used to perform repeated measures ANOVA.</p>
<div class="sourceCode" id="cb495"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb495-1"><a href="basic-statistics.html#cb495-1" aria-hidden="true" tabindex="-1"></a>auc_df <span class="sc">%&gt;%</span> <span class="fu">anova_test</span>(AUC_Cbratio <span class="sc">~</span> Day, <span class="at">wid =</span> Subject,</span>
<span id="cb495-2"><a href="basic-statistics.html#cb495-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">within =</span> Day)</span></code></pre></div>
<pre><code>## Coefficient covariances computed by hccm()</code></pre>
<pre><code>## ANOVA Table (type II tests)
## 
##   Effect DFn DFd     F     p p&lt;.05  ges
## 1    Day   4  45 0.588 0.673       0.05</code></pre>
<p><code>wid</code> is the column name containing individuals/subjects identifiers. It should be unique to each individual. <code>within</code> is an <strong>optional</strong> argument that contains within subject variable, which in this case is <code>Day</code> as the same subjects were tested across days.</p>
<p>If different subjects were tested on each day, then <code>wid</code> should be empty. In both occasions, the p-value is the same because the subject identifiers (ex. <code>S1</code>, <code>S2</code>) are unique to each subject. Therefore, <code>R</code> just recognizes that it should perform repeated measures ANOVA.</p>
</div>
</div>
<div id="two-way-anova" class="section level2" number="10.7">
<h2><span class="header-section-number">10.7</span> Two-way ANOVA</h2>
<p>In a two-way ANOVA, the effects of two factors are examined. In our example, we will use the data set from the paper, and examine the effects of <code>Day</code> and <code>Time</code>, which is the time point after short-term monocular deprivation (minutes).</p>
<p>Since we will be investigating whether the effects of <code>Day</code> and <code>Time</code> as variables significantly affect the values of <code>Cbratio</code>, we need to convert the columns <code>Day</code> and <code>Time</code> of <code>df</code> as factor using <code>as.factor()</code>.</p>
<div class="sourceCode" id="cb498"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb498-1"><a href="basic-statistics.html#cb498-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&#39;https://www.smin95.com/min2019b.csv&#39;</span>) </span></code></pre></div>
<pre><code>## Rows: 300 Columns: 4
## -- Column specification --------------------------------------------------------
## Delimiter: &quot;,&quot;
## chr (1): Subject
## dbl (3): Day, Time, Cbratio
## 
## i Use `spec()` to retrieve the full column specification for this data.
## i Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb500"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb500-1"><a href="basic-statistics.html#cb500-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Day <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>Day)</span>
<span id="cb500-2"><a href="basic-statistics.html#cb500-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Time <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>Time)</span></code></pre></div>
<p>As before, let’s check for some of the assumptions that are required to perform ANOVA.</p>
<div id="identifying-outliers" class="section level3" number="10.7.1">
<h3><span class="header-section-number">10.7.1</span> Identifying Outliers</h3>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="basic-statistics.html#cb501-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Day, Time) <span class="sc">%&gt;%</span></span>
<span id="cb501-2"><a href="basic-statistics.html#cb501-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">identify_outliers</span>(Cbratio)</span></code></pre></div>
<pre><code>## # A tibble: 13 x 6
##    Day   Time  Subject Cbratio is.outlier is.extreme
##    &lt;fct&gt; &lt;fct&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;lgl&gt;      &lt;lgl&gt;     
##  1 1     12    f         3.43  TRUE       FALSE     
##  2 2     24    d        -0.916 TRUE       FALSE     
##  3 2     24    e         5.20  TRUE       TRUE      
##  4 2     48    j         2.75  TRUE       FALSE     
##  5 3     24    b         2.79  TRUE       FALSE     
##  6 3     24    u        -0.389 TRUE       FALSE     
##  7 4     0     f         7.47  TRUE       FALSE     
##  8 4     3     e         8.70  TRUE       TRUE      
##  9 4     6     f         2.38  TRUE       FALSE     
## 10 4     24    g         3.45  TRUE       FALSE     
## 11 4     48    e        -2.37  TRUE       FALSE     
## 12 4     48    g         3.21  TRUE       FALSE     
## 13 5     6     d        -2.88  TRUE       TRUE</code></pre>
<p>We observe that there are 13 outliers, 2 of which are considered to be extreme points. <code>identify_outliers()</code> pinpoint outliers based on the definition of boxplots. Outliers in boxplots can be ignored. However, extreme points can be considered to be slightly troublesome. In this example, 2 out of 230 (<code>nrow(df)</code>) observations seem to be extreme points. Therefore, the data set meets the requirement to be analyzed using two-way ANOVA.</p>
</div>
<div id="checking-for-normality-of-data-1" class="section level3" number="10.7.2">
<h3><span class="header-section-number">10.7.2</span> Checking for Normality of Data</h3>
<p>Let’s check for the normality of the data using <code>shapiro_test()</code> from the <code>rstatix</code> package for each <code>Day</code> and <code>Time</code>. To do so, we will have to group our data using <code>group_by()</code> for <code>Day</code> and <code>Time</code>.</p>
<div class="sourceCode" id="cb503"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb503-1"><a href="basic-statistics.html#cb503-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Day, Time) <span class="sc">%&gt;%</span></span>
<span id="cb503-2"><a href="basic-statistics.html#cb503-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro_test</span>(Cbratio)</span></code></pre></div>
<pre><code>## # A tibble: 30 x 5
##    Day   Time  variable statistic     p
##    &lt;fct&gt; &lt;fct&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;
##  1 1     0     Cbratio      0.913 0.306
##  2 1     3     Cbratio      0.947 0.630
##  3 1     6     Cbratio      0.899 0.213
##  4 1     12    Cbratio      0.897 0.201
##  5 1     24    Cbratio      0.918 0.341
##  6 1     48    Cbratio      0.964 0.831
##  7 2     0     Cbratio      0.925 0.398
##  8 2     3     Cbratio      0.912 0.292
##  9 2     6     Cbratio      0.900 0.221
## 10 2     12    Cbratio      0.934 0.493
## # ... with 20 more rows</code></pre>
<p>Only the first 10 rows are shown. To view the entire results, store the results into a variable and use <code>View()</code>.</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="basic-statistics.html#cb505-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Day, Time) <span class="sc">%&gt;%</span></span>
<span id="cb505-2"><a href="basic-statistics.html#cb505-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shapiro_test</span>(Cbratio)</span></code></pre></div>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="basic-statistics.html#cb506-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(res)</span></code></pre></div>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="basic-statistics.html#cb507-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(res<span class="sc">$</span>p <span class="sc">&lt;</span> <span class="fl">0.05</span>)</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>We see that there are 3 p-values (out of 30 combinations of <code>Day</code> and <code>Time</code>) that are smaller than 0.05. Ideally, we would want all of them to have a p-value higher than 0.05 for the data to be considered as normally distributed. However, since most data seem to be normally distributed in our example, it is okay to proceed to use a two-way ANOVA, which is a parametric procedure.</p>
</div>
<div id="computing-two-way-anova" class="section level3" number="10.7.3">
<h3><span class="header-section-number">10.7.3</span> Computing Two-way ANOVA</h3>
<p>As before, let’s use <code>aov()</code> function to compute ANOVA.</p>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb509-1"><a href="basic-statistics.html#cb509-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">formula =</span> Cbratio <span class="sc">~</span> Day <span class="sc">+</span> Time <span class="sc">+</span> Day<span class="sc">:</span>Time,</span>
<span id="cb509-2"><a href="basic-statistics.html#cb509-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df)</span>
<span id="cb509-3"><a href="basic-statistics.html#cb509-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res)</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Day           4    7.2   1.796   0.948    0.437    
## Time          5   74.2  14.832   7.825 6.77e-07 ***
## Day:Time     20   18.4   0.921   0.486    0.971    
## Residuals   270  511.8   1.896                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As before, we specify the <code>formula</code> using tilde (<code>~</code>); its left side is the dependent variable (<code>Cbratio</code>), and the right side includes the independent variables (or predictors, ex. <code>Day</code> and <code>Time</code>). <code>+</code> is used to add more independent variables in the model formula. Interaction between the effects of <code>Day</code> and <code>Time</code> should also be included by <code>:</code>.</p>
<p>Another way of writing the model formula is shown below. It uses <code>*</code> as a shortcut to include the effects of <code>Day</code>, <code>Time</code> and their interactions. Notice that the results of both ANOVAs are identical because the model formulas are the same.</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb511-1"><a href="basic-statistics.html#cb511-1" aria-hidden="true" tabindex="-1"></a>res2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="at">formula =</span> Cbratio <span class="sc">~</span> Day<span class="sc">*</span>Time, <span class="at">data =</span> df)</span>
<span id="cb511-2"><a href="basic-statistics.html#cb511-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(res2)</span></code></pre></div>
<pre><code>##              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Day           4    7.2   1.796   0.948    0.437    
## Time          5   74.2  14.832   7.825 6.77e-07 ***
## Day:Time     20   18.4   0.921   0.486    0.971    
## Residuals   270  511.8   1.896                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>It appears that there is a statistically significant effect of <code>Time</code>, F(5, 270) = 7.83, p &lt; 0.001. But the effect of <code>Day</code> seems to be not significant, F(4,270) = 0.49, p = 0.44. Also the effect of interaction between <code>Day</code> and <code>Time</code> is not significant, F(20,270) = 0.97, p &gt; 0.05.</p>
<p>An interaction effect between A and B exists when the effect of factor A (ex. <code>Day</code>) is different at different levels of factor B (ex. <code>Time</code>). Let’s understand how the effect of interaction could affect the data.</p>
<p><img src="bookdownproj_files/figure-html/unnamed-chunk-365-1.png" width="336" /></p>
<p>We see that best-fit regression slopes of the green, red and purple lines are almost identical. This is because the factor <code>Time</code> affects <code>Cbratio</code> at different levels of the factor <code>Day</code> (i.e., different days). This suggests that the slope of decay (decrease in changes in Contrast balance ratio) over time is similar across days. In other words, the interaction effect between <code>Time</code> and <code>Day</code> is not significant (p &lt; 0.05).</p>
<p>Conversely, if <code>Time</code> affects <code>Cbratio</code> differently across different days, we would see that the best-fit regression slopes would be different among days.</p>
</div>
<div id="post-hoc-test" class="section level3" number="10.7.4">
<h3><span class="header-section-number">10.7.4</span> Post-hoc Test</h3>
<p>The procedure for post-hoc analysis differs depending on whether the interaction effect is statistically significant (p &lt; 0.05) or not (p &gt; 0.05).</p>
<p>Post-hoc test should be performed when there is a significant main effect from one of the factors (ex. <code>Time</code> or <code>Day</code>) in the two-way ANOVA. If not, it should not be performed.</p>
<p>If there is a significant main effect but the interaction effect is not significant, only interpret the results of post-hoc analysis that are related to the main effects. For example, if <code>Time</code> was a significant main effect, we could analyze the data as following.</p>
<div class="sourceCode" id="cb513"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb513-1"><a href="basic-statistics.html#cb513-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(res, <span class="at">which =</span> <span class="st">&#39;Time&#39;</span>)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Cbratio ~ Day + Time + Day:Time, data = df)
## 
## $Time
##            diff        lwr         upr     p adj
## 3-0    0.106096 -0.6842609  0.89645292 0.9988910
## 6-0   -0.378016 -1.1683729  0.41234092 0.7432954
## 12-0  -0.887696 -1.6780529 -0.09733908 0.0176431
## 24-0  -0.876150 -1.6665069 -0.08579308 0.0201057
## 48-0  -1.257262 -2.0476189 -0.46690508 0.0001098
## 6-3   -0.484112 -1.2744689  0.30624492 0.4946934
## 12-3  -0.993792 -1.7841489 -0.20343508 0.0048793
## 24-3  -0.982246 -1.7726029 -0.19188908 0.0056524
## 48-3  -1.363358 -2.1537149 -0.57300108 0.0000191
## 12-6  -0.509680 -1.3000369  0.28067692 0.4349141
## 24-6  -0.498134 -1.2884909  0.29222292 0.4616410
## 48-6  -0.879246 -1.6696029 -0.08888908 0.0194170
## 24-12  0.011546 -0.7788109  0.80190292 1.0000000
## 48-12 -0.369566 -1.1599229  0.42079092 0.7611911
## 48-24 -0.381112 -1.1714689  0.40924492 0.7366165</code></pre>
<p>If there is a significant interaction effect between <code>Day</code> and <code>Time</code>, we can examine how the effect of <code>Time</code> varies across different days.</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb515-1"><a href="basic-statistics.html#cb515-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Day) <span class="sc">%&gt;%</span></span>
<span id="cb515-2"><a href="basic-statistics.html#cb515-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova_test</span>(Cbratio <span class="sc">~</span> Time, <span class="at">wid =</span> Subject, <span class="at">within =</span> Day) <span class="sc">%&gt;%</span></span>
<span id="cb515-3"><a href="basic-statistics.html#cb515-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_anova_table</span>() <span class="sc">%&gt;%</span></span>
<span id="cb515-4"><a href="basic-statistics.html#cb515-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adjust_pvalue</span>(<span class="at">method =</span> <span class="st">&#39;bonferroni&#39;</span>)</span></code></pre></div>
<pre><code>## Coefficient covariances computed by hccm()
## Coefficient covariances computed by hccm()
## Coefficient covariances computed by hccm()
## Coefficient covariances computed by hccm()
## Coefficient covariances computed by hccm()</code></pre>
<pre><code>## # A tibble: 5 x 9
##     Day Effect   DFn   DFd     F        p `p&lt;.05`   ges   p.adj
##   &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt;   &lt;dbl&gt;
## 1     1 Time       1    58  3.73 0.058    &quot;&quot;      0.06  0.29   
## 2     2 Time       1    58  5    0.029    &quot;*&quot;     0.079 0.145  
## 3     3 Time       1    58 17.4  0.000104 &quot;*&quot;     0.23  0.00052
## 4     4 Time       1    58  3.96 0.051    &quot;&quot;      0.064 0.255  
## 5     5 Time       1    58  6.9  0.011    &quot;*&quot;     0.106 0.055</code></pre>
<p><code>within</code> refers to the within-subject factor, which in this case <code>Day</code>. If there are different subjects associated with each <code>Day</code>, then <code>between</code> argument can be filled instead of <code>within</code> in the <code>anova_test()</code> function.</p>
<p>It seems that the effect of <code>Time</code> is not statistically significant at different levels of the factor <code>Day</code>, except for Day 3. This means that the decrease of <code>Cbratio</code> over time does not differ significantly across most days. This (sort of) agrees with our results that the interaction effect is not statistically significant.</p>
<p>Let’s pretend that the interaction effect is still significant. If so, we can examine whether the second independent variable (<code>Day</code> in our case) differs across different levels of the first independent variable (<code>Time</code> in our example).</p>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb518-1"><a href="basic-statistics.html#cb518-1" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Time) <span class="sc">%&gt;%</span></span>
<span id="cb518-2"><a href="basic-statistics.html#cb518-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">anova_test</span>(Cbratio <span class="sc">~</span> Day, <span class="at">wid =</span> Subject, <span class="at">within =</span> Time) <span class="sc">%&gt;%</span></span>
<span id="cb518-3"><a href="basic-statistics.html#cb518-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_anova_table</span>() <span class="sc">%&gt;%</span></span>
<span id="cb518-4"><a href="basic-statistics.html#cb518-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">adjust_pvalue</span>(<span class="at">method =</span> <span class="st">&#39;bonferroni&#39;</span>)</span></code></pre></div>
<pre><code>## Coefficient covariances computed by hccm()
## Coefficient covariances computed by hccm()
## Coefficient covariances computed by hccm()
## Coefficient covariances computed by hccm()
## Coefficient covariances computed by hccm()
## Coefficient covariances computed by hccm()</code></pre>
<pre><code>## # A tibble: 6 x 9
##    Time Effect   DFn   DFd     F     p `p&lt;.05`   ges p.adj
##   &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1     0 Day        1    48 0.36  0.551 &quot;&quot;      0.007 1    
## 2     3 Day        1    48 1.10  0.3   &quot;&quot;      0.022 1    
## 3     6 Day        1    48 7.88  0.007 &quot;*&quot;     0.141 0.042
## 4    12 Day        1    48 0.058 0.811 &quot;&quot;      0.001 1    
## 5    24 Day        1    48 1.54  0.221 &quot;&quot;      0.031 1    
## 6    48 Day        1    48 1.25  0.268 &quot;&quot;      0.025 1</code></pre>
<p>It seems that the effect of <code>Day</code> remains insignificant across all time points.</p>
<p>You may realize that this result from the above is strange. Indeed, it is inappropriate to report these two results because the interaction effect is not statistically significant. Therefore, it is more appropriate to just report the post-hoc analysis that is only concerned with the effect of <code>Time</code>.</p>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb521-1"><a href="basic-statistics.html#cb521-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(res, <span class="at">which =</span> <span class="st">&#39;Time&#39;</span>)</span></code></pre></div>
<pre><code>##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = Cbratio ~ Day + Time + Day:Time, data = df)
## 
## $Time
##            diff        lwr         upr     p adj
## 3-0    0.106096 -0.6842609  0.89645292 0.9988910
## 6-0   -0.378016 -1.1683729  0.41234092 0.7432954
## 12-0  -0.887696 -1.6780529 -0.09733908 0.0176431
## 24-0  -0.876150 -1.6665069 -0.08579308 0.0201057
## 48-0  -1.257262 -2.0476189 -0.46690508 0.0001098
## 6-3   -0.484112 -1.2744689  0.30624492 0.4946934
## 12-3  -0.993792 -1.7841489 -0.20343508 0.0048793
## 24-3  -0.982246 -1.7726029 -0.19188908 0.0056524
## 48-3  -1.363358 -2.1537149 -0.57300108 0.0000191
## 12-6  -0.509680 -1.3000369  0.28067692 0.4349141
## 24-6  -0.498134 -1.2884909  0.29222292 0.4616410
## 48-6  -0.879246 -1.6696029 -0.08888908 0.0194170
## 24-12  0.011546 -0.7788109  0.80190292 1.0000000
## 48-12 -0.369566 -1.1599229  0.42079092 0.7611911
## 48-24 -0.381112 -1.1714689  0.40924492 0.7366165</code></pre>
</div>
</div>
<div id="extra-resources" class="section level2" number="10.8">
<h2><span class="header-section-number">10.8</span> Extra Resources</h2>
<p>For detailed information about ANOVA in R, please check out this link: <a href="https://www.datanovia.com/en/lessons/anova-in-r/" class="uri">https://www.datanovia.com/en/lessons/anova-in-r/</a>.</p>
<p>To learn more about performing statistical tests in R, please check out the book entitled <strong>YaRrr! The Pirate’s Guide to R</strong> by Nathaniel Phillips (<a href="https://bookdown.org/ndphillips/YaRrr/" class="uri">https://bookdown.org/ndphillips/YaRrr/</a>).</p>

</div>
</div>



            </section>

          </div>
        </div>
      </div>
<a href="calculating-linear-slopes.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="themes-colors-correlations-boxplots-violins-and-bars-part-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/smin95/dataviz/edit/master/statistics.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": "https://github.com/smin95/dataviz/blob/master/statistics.Rmd",
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
